// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: byte/v/forge/contracts/proxyruntime/v1/proxy_runtime.proto

/* eslint-disable */
import type { SecretRef } from "../../common/v1/common";

export const protobufPackage = "byte.v.forge.contracts.proxyruntime.v1";

export enum ProxyProtocol {
  PROXY_PROTOCOL_UNSPECIFIED = "PROXY_PROTOCOL_UNSPECIFIED",
  PROXY_PROTOCOL_HTTP = "PROXY_PROTOCOL_HTTP",
  PROXY_PROTOCOL_SOCKS5 = "PROXY_PROTOCOL_SOCKS5",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ProxyCapability {
  PROXY_CAPABILITY_UNSPECIFIED = "PROXY_CAPABILITY_UNSPECIFIED",
  PROXY_CAPABILITY_POOL_REFRESH = "PROXY_CAPABILITY_POOL_REFRESH",
  PROXY_CAPABILITY_API_POOL = "PROXY_CAPABILITY_API_POOL",
  PROXY_CAPABILITY_STICKY_SESSION = "PROXY_CAPABILITY_STICKY_SESSION",
  PROXY_CAPABILITY_ACTIVE_SESSION_ROTATION = "PROXY_CAPABILITY_ACTIVE_SESSION_ROTATION",
  PROXY_CAPABILITY_USERNAME_PARAMETER_SESSION = "PROXY_CAPABILITY_USERNAME_PARAMETER_SESSION",
  PROXY_CAPABILITY_UNIFIED_EGRESS_GATEWAY = "PROXY_CAPABILITY_UNIFIED_EGRESS_GATEWAY",
  PROXY_CAPABILITY_DYNAMIC_LEASE = "PROXY_CAPABILITY_DYNAMIC_LEASE",
  PROXY_CAPABILITY_SUBSCRIPTION_PROVIDER = "PROXY_CAPABILITY_SUBSCRIPTION_PROVIDER",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ProxySessionMode {
  PROXY_SESSION_MODE_UNSPECIFIED = "PROXY_SESSION_MODE_UNSPECIFIED",
  PROXY_SESSION_MODE_ROTATING = "PROXY_SESSION_MODE_ROTATING",
  PROXY_SESSION_MODE_STICKY = "PROXY_SESSION_MODE_STICKY",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ProxyUpstreamKind {
  PROXY_UPSTREAM_KIND_UNSPECIFIED = "PROXY_UPSTREAM_KIND_UNSPECIFIED",
  PROXY_UPSTREAM_KIND_SIMPLE_PROXY = "PROXY_UPSTREAM_KIND_SIMPLE_PROXY",
  PROXY_UPSTREAM_KIND_DYNAMIC_IP = "PROXY_UPSTREAM_KIND_DYNAMIC_IP",
  PROXY_UPSTREAM_KIND_PROXY_POOL = "PROXY_UPSTREAM_KIND_PROXY_POOL",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ProxySourceKind {
  PROXY_SOURCE_KIND_UNSPECIFIED = "PROXY_SOURCE_KIND_UNSPECIFIED",
  PROXY_SOURCE_KIND_FIXED_PROXY = "PROXY_SOURCE_KIND_FIXED_PROXY",
  PROXY_SOURCE_KIND_SUBSCRIPTION = "PROXY_SOURCE_KIND_SUBSCRIPTION",
  PROXY_SOURCE_KIND_API_POOL = "PROXY_SOURCE_KIND_API_POOL",
  PROXY_SOURCE_KIND_DYNAMIC_IP = "PROXY_SOURCE_KIND_DYNAMIC_IP",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ProxyKind {
  PROXY_KIND_UNSPECIFIED = "PROXY_KIND_UNSPECIFIED",
  PROXY_KIND_DYNAMIC_IP = "PROXY_KIND_DYNAMIC_IP",
  PROXY_KIND_STATIC_IP = "PROXY_KIND_STATIC_IP",
  PROXY_KIND_SUBSCRIPTION = "PROXY_KIND_SUBSCRIPTION",
  PROXY_KIND_FIXED_PROXY = "PROXY_KIND_FIXED_PROXY",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ProxySourceNodeStatus {
  PROXY_SOURCE_NODE_STATUS_UNSPECIFIED = "PROXY_SOURCE_NODE_STATUS_UNSPECIFIED",
  PROXY_SOURCE_NODE_STATUS_UNKNOWN = "PROXY_SOURCE_NODE_STATUS_UNKNOWN",
  PROXY_SOURCE_NODE_STATUS_AVAILABLE = "PROXY_SOURCE_NODE_STATUS_AVAILABLE",
  PROXY_SOURCE_NODE_STATUS_UNAVAILABLE = "PROXY_SOURCE_NODE_STATUS_UNAVAILABLE",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ProxyRotationMode {
  PROXY_ROTATION_MODE_UNSPECIFIED = "PROXY_ROTATION_MODE_UNSPECIFIED",
  PROXY_ROTATION_MODE_NONE = "PROXY_ROTATION_MODE_NONE",
  PROXY_ROTATION_MODE_PER_REQUEST = "PROXY_ROTATION_MODE_PER_REQUEST",
  PROXY_ROTATION_MODE_STICKY_SESSION = "PROXY_ROTATION_MODE_STICKY_SESSION",
  PROXY_ROTATION_MODE_SCHEDULED_POOL_REFRESH = "PROXY_ROTATION_MODE_SCHEDULED_POOL_REFRESH",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ProxyRouteRuntimeKind {
  PROXY_ROUTE_RUNTIME_KIND_UNSPECIFIED = "PROXY_ROUTE_RUNTIME_KIND_UNSPECIFIED",
  PROXY_ROUTE_RUNTIME_KIND_GOST = "PROXY_ROUTE_RUNTIME_KIND_GOST",
  PROXY_ROUTE_RUNTIME_KIND_MIHOMO = "PROXY_ROUTE_RUNTIME_KIND_MIHOMO",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ProxySourceRuntimeKind {
  PROXY_SOURCE_RUNTIME_KIND_UNSPECIFIED = "PROXY_SOURCE_RUNTIME_KIND_UNSPECIFIED",
  PROXY_SOURCE_RUNTIME_KIND_NONE = "PROXY_SOURCE_RUNTIME_KIND_NONE",
  PROXY_SOURCE_RUNTIME_KIND_MIHOMO = "PROXY_SOURCE_RUNTIME_KIND_MIHOMO",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ProxyProviderAccountStatus {
  PROXY_PROVIDER_ACCOUNT_STATUS_UNSPECIFIED = "PROXY_PROVIDER_ACCOUNT_STATUS_UNSPECIFIED",
  PROXY_PROVIDER_ACCOUNT_STATUS_ENABLED = "PROXY_PROVIDER_ACCOUNT_STATUS_ENABLED",
  PROXY_PROVIDER_ACCOUNT_STATUS_DISABLED = "PROXY_PROVIDER_ACCOUNT_STATUS_DISABLED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ProxyDynamicLeaseStatus {
  PROXY_DYNAMIC_LEASE_STATUS_UNSPECIFIED = "PROXY_DYNAMIC_LEASE_STATUS_UNSPECIFIED",
  PROXY_DYNAMIC_LEASE_STATUS_ACTIVE = "PROXY_DYNAMIC_LEASE_STATUS_ACTIVE",
  PROXY_DYNAMIC_LEASE_STATUS_EXPIRED = "PROXY_DYNAMIC_LEASE_STATUS_EXPIRED",
  PROXY_DYNAMIC_LEASE_STATUS_FAILED = "PROXY_DYNAMIC_LEASE_STATUS_FAILED",
  PROXY_DYNAMIC_LEASE_STATUS_RELEASED = "PROXY_DYNAMIC_LEASE_STATUS_RELEASED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ProxyIPNetworkKind {
  PROXY_IP_NETWORK_KIND_UNSPECIFIED = "PROXY_IP_NETWORK_KIND_UNSPECIFIED",
  PROXY_IP_NETWORK_KIND_UNKNOWN = "PROXY_IP_NETWORK_KIND_UNKNOWN",
  PROXY_IP_NETWORK_KIND_RESIDENTIAL = "PROXY_IP_NETWORK_KIND_RESIDENTIAL",
  PROXY_IP_NETWORK_KIND_DATACENTER = "PROXY_IP_NETWORK_KIND_DATACENTER",
  PROXY_IP_NETWORK_KIND_MOBILE = "PROXY_IP_NETWORK_KIND_MOBILE",
  PROXY_IP_NETWORK_KIND_ISP = "PROXY_IP_NETWORK_KIND_ISP",
  PROXY_IP_NETWORK_KIND_BUSINESS = "PROXY_IP_NETWORK_KIND_BUSINESS",
  PROXY_IP_NETWORK_KIND_SATELLITE = "PROXY_IP_NETWORK_KIND_SATELLITE",
  PROXY_IP_NETWORK_KIND_BROADCAST = "PROXY_IP_NETWORK_KIND_BROADCAST",
  PROXY_IP_NETWORK_KIND_ANYCAST = "PROXY_IP_NETWORK_KIND_ANYCAST",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ProxyIPAnonymizerKind {
  PROXY_IP_ANONYMIZER_KIND_UNSPECIFIED = "PROXY_IP_ANONYMIZER_KIND_UNSPECIFIED",
  PROXY_IP_ANONYMIZER_KIND_UNKNOWN = "PROXY_IP_ANONYMIZER_KIND_UNKNOWN",
  PROXY_IP_ANONYMIZER_KIND_NONE = "PROXY_IP_ANONYMIZER_KIND_NONE",
  PROXY_IP_ANONYMIZER_KIND_PROXY = "PROXY_IP_ANONYMIZER_KIND_PROXY",
  PROXY_IP_ANONYMIZER_KIND_VPN = "PROXY_IP_ANONYMIZER_KIND_VPN",
  PROXY_IP_ANONYMIZER_KIND_TOR = "PROXY_IP_ANONYMIZER_KIND_TOR",
  PROXY_IP_ANONYMIZER_KIND_CRAWLER = "PROXY_IP_ANONYMIZER_KIND_CRAWLER",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ProxyIPFraudRiskLevel {
  PROXY_IP_FRAUD_RISK_LEVEL_UNSPECIFIED = "PROXY_IP_FRAUD_RISK_LEVEL_UNSPECIFIED",
  PROXY_IP_FRAUD_RISK_LEVEL_UNKNOWN = "PROXY_IP_FRAUD_RISK_LEVEL_UNKNOWN",
  PROXY_IP_FRAUD_RISK_LEVEL_LOW = "PROXY_IP_FRAUD_RISK_LEVEL_LOW",
  PROXY_IP_FRAUD_RISK_LEVEL_MEDIUM = "PROXY_IP_FRAUD_RISK_LEVEL_MEDIUM",
  PROXY_IP_FRAUD_RISK_LEVEL_HIGH = "PROXY_IP_FRAUD_RISK_LEVEL_HIGH",
  PROXY_IP_FRAUD_RISK_LEVEL_CRITICAL = "PROXY_IP_FRAUD_RISK_LEVEL_CRITICAL",
  PROXY_IP_FRAUD_RISK_LEVEL_UNSUPPORTED = "PROXY_IP_FRAUD_RISK_LEVEL_UNSUPPORTED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ProxyIPFraudSignal {
  PROXY_IP_FRAUD_SIGNAL_UNSPECIFIED = "PROXY_IP_FRAUD_SIGNAL_UNSPECIFIED",
  PROXY_IP_FRAUD_SIGNAL_BOGON = "PROXY_IP_FRAUD_SIGNAL_BOGON",
  PROXY_IP_FRAUD_SIGNAL_DATACENTER = "PROXY_IP_FRAUD_SIGNAL_DATACENTER",
  PROXY_IP_FRAUD_SIGNAL_HOSTING = "PROXY_IP_FRAUD_SIGNAL_HOSTING",
  PROXY_IP_FRAUD_SIGNAL_PROXY = "PROXY_IP_FRAUD_SIGNAL_PROXY",
  PROXY_IP_FRAUD_SIGNAL_VPN = "PROXY_IP_FRAUD_SIGNAL_VPN",
  PROXY_IP_FRAUD_SIGNAL_TOR = "PROXY_IP_FRAUD_SIGNAL_TOR",
  PROXY_IP_FRAUD_SIGNAL_ABUSER = "PROXY_IP_FRAUD_SIGNAL_ABUSER",
  PROXY_IP_FRAUD_SIGNAL_CRAWLER = "PROXY_IP_FRAUD_SIGNAL_CRAWLER",
  PROXY_IP_FRAUD_SIGNAL_MOBILE = "PROXY_IP_FRAUD_SIGNAL_MOBILE",
  PROXY_IP_FRAUD_SIGNAL_SATELLITE = "PROXY_IP_FRAUD_SIGNAL_SATELLITE",
  PROXY_IP_FRAUD_SIGNAL_BROADCAST = "PROXY_IP_FRAUD_SIGNAL_BROADCAST",
  PROXY_IP_FRAUD_SIGNAL_ANYCAST = "PROXY_IP_FRAUD_SIGNAL_ANYCAST",
  PROXY_IP_FRAUD_SIGNAL_FRAUD_CHECK_UNSUPPORTED = "PROXY_IP_FRAUD_SIGNAL_FRAUD_CHECK_UNSUPPORTED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ProxyIPFraudProviderKind {
  PROXY_IP_FRAUD_PROVIDER_KIND_UNSPECIFIED = "PROXY_IP_FRAUD_PROVIDER_KIND_UNSPECIFIED",
  PROXY_IP_FRAUD_PROVIDER_KIND_IPAPI = "PROXY_IP_FRAUD_PROVIDER_KIND_IPAPI",
  PROXY_IP_FRAUD_PROVIDER_KIND_IPINFO = "PROXY_IP_FRAUD_PROVIDER_KIND_IPINFO",
  PROXY_IP_FRAUD_PROVIDER_KIND_IP2LOCATION = "PROXY_IP_FRAUD_PROVIDER_KIND_IP2LOCATION",
  PROXY_IP_FRAUD_PROVIDER_KIND_IP_API_COM = "PROXY_IP_FRAUD_PROVIDER_KIND_IP_API_COM",
  PROXY_IP_FRAUD_PROVIDER_KIND_IPQUALITYSCORE = "PROXY_IP_FRAUD_PROVIDER_KIND_IPQUALITYSCORE",
  PROXY_IP_FRAUD_PROVIDER_KIND_ABUSEIPDB = "PROXY_IP_FRAUD_PROVIDER_KIND_ABUSEIPDB",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ProxyEdgeAccessRiskLevel {
  PROXY_EDGE_ACCESS_RISK_LEVEL_UNSPECIFIED = "PROXY_EDGE_ACCESS_RISK_LEVEL_UNSPECIFIED",
  PROXY_EDGE_ACCESS_RISK_LEVEL_UNKNOWN = "PROXY_EDGE_ACCESS_RISK_LEVEL_UNKNOWN",
  PROXY_EDGE_ACCESS_RISK_LEVEL_LOW = "PROXY_EDGE_ACCESS_RISK_LEVEL_LOW",
  PROXY_EDGE_ACCESS_RISK_LEVEL_MEDIUM = "PROXY_EDGE_ACCESS_RISK_LEVEL_MEDIUM",
  PROXY_EDGE_ACCESS_RISK_LEVEL_HIGH = "PROXY_EDGE_ACCESS_RISK_LEVEL_HIGH",
  PROXY_EDGE_ACCESS_RISK_LEVEL_CHALLENGE_LIKELY = "PROXY_EDGE_ACCESS_RISK_LEVEL_CHALLENGE_LIKELY",
  PROXY_EDGE_ACCESS_RISK_LEVEL_BLOCK_LIKELY = "PROXY_EDGE_ACCESS_RISK_LEVEL_BLOCK_LIKELY",
  PROXY_EDGE_ACCESS_RISK_LEVEL_UNSUPPORTED = "PROXY_EDGE_ACCESS_RISK_LEVEL_UNSUPPORTED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ProxyEdgeAccessRiskSignal {
  PROXY_EDGE_ACCESS_RISK_SIGNAL_UNSPECIFIED = "PROXY_EDGE_ACCESS_RISK_SIGNAL_UNSPECIFIED",
  PROXY_EDGE_ACCESS_RISK_SIGNAL_IP_REPUTATION_RISK = "PROXY_EDGE_ACCESS_RISK_SIGNAL_IP_REPUTATION_RISK",
  PROXY_EDGE_ACCESS_RISK_SIGNAL_DATACENTER_NETWORK = "PROXY_EDGE_ACCESS_RISK_SIGNAL_DATACENTER_NETWORK",
  PROXY_EDGE_ACCESS_RISK_SIGNAL_ANONYMIZER_DETECTED = "PROXY_EDGE_ACCESS_RISK_SIGNAL_ANONYMIZER_DETECTED",
  PROXY_EDGE_ACCESS_RISK_SIGNAL_GEO_MISMATCH = "PROXY_EDGE_ACCESS_RISK_SIGNAL_GEO_MISMATCH",
  PROXY_EDGE_ACCESS_RISK_SIGNAL_EDGE_ACCESS_PASSED = "PROXY_EDGE_ACCESS_RISK_SIGNAL_EDGE_ACCESS_PASSED",
  PROXY_EDGE_ACCESS_RISK_SIGNAL_EDGE_CHALLENGE_DETECTED = "PROXY_EDGE_ACCESS_RISK_SIGNAL_EDGE_CHALLENGE_DETECTED",
  PROXY_EDGE_ACCESS_RISK_SIGNAL_EDGE_BLOCK_DETECTED = "PROXY_EDGE_ACCESS_RISK_SIGNAL_EDGE_BLOCK_DETECTED",
  PROXY_EDGE_ACCESS_RISK_SIGNAL_EDGE_RATE_LIMIT_DETECTED = "PROXY_EDGE_ACCESS_RISK_SIGNAL_EDGE_RATE_LIMIT_DETECTED",
  PROXY_EDGE_ACCESS_RISK_SIGNAL_EDGE_UNAVAILABLE = "PROXY_EDGE_ACCESS_RISK_SIGNAL_EDGE_UNAVAILABLE",
  PROXY_EDGE_ACCESS_RISK_SIGNAL_EDGE_ACCESS_UNSUPPORTED = "PROXY_EDGE_ACCESS_RISK_SIGNAL_EDGE_ACCESS_UNSUPPORTED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ProxySelectorStrategy {
  PROXY_SELECTOR_STRATEGY_UNSPECIFIED = "PROXY_SELECTOR_STRATEGY_UNSPECIFIED",
  PROXY_SELECTOR_STRATEGY_ROUND_ROBIN = "PROXY_SELECTOR_STRATEGY_ROUND_ROBIN",
  PROXY_SELECTOR_STRATEGY_RANDOM = "PROXY_SELECTOR_STRATEGY_RANDOM",
  PROXY_SELECTOR_STRATEGY_FIFO = "PROXY_SELECTOR_STRATEGY_FIFO",
  PROXY_SELECTOR_STRATEGY_HASH_CLIENT_IP = "PROXY_SELECTOR_STRATEGY_HASH_CLIENT_IP",
  PROXY_SELECTOR_STRATEGY_HASH_TARGET_HOST = "PROXY_SELECTOR_STRATEGY_HASH_TARGET_HOST",
  PROXY_SELECTOR_STRATEGY_FALLBACK = "PROXY_SELECTOR_STRATEGY_FALLBACK",
  PROXY_SELECTOR_STRATEGY_URL_TEST = "PROXY_SELECTOR_STRATEGY_URL_TEST",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum EgressProfileLineKind {
  EGRESS_PROFILE_LINE_KIND_UNSPECIFIED = "EGRESS_PROFILE_LINE_KIND_UNSPECIFIED",
  EGRESS_PROFILE_LINE_KIND_DIRECT = "EGRESS_PROFILE_LINE_KIND_DIRECT",
  EGRESS_PROFILE_LINE_KIND_SOURCE = "EGRESS_PROFILE_LINE_KIND_SOURCE",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum EgressProfileExitKind {
  EGRESS_PROFILE_EXIT_KIND_UNSPECIFIED = "EGRESS_PROFILE_EXIT_KIND_UNSPECIFIED",
  EGRESS_PROFILE_EXIT_KIND_DIRECT = "EGRESS_PROFILE_EXIT_KIND_DIRECT",
  EGRESS_PROFILE_EXIT_KIND_STATIC_IP = "EGRESS_PROFILE_EXIT_KIND_STATIC_IP",
  EGRESS_PROFILE_EXIT_KIND_DYNAMIC_IP = "EGRESS_PROFILE_EXIT_KIND_DYNAMIC_IP",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum EgressHopRole {
  EGRESS_HOP_ROLE_UNSPECIFIED = "EGRESS_HOP_ROLE_UNSPECIFIED",
  EGRESS_HOP_ROLE_FORWARD = "EGRESS_HOP_ROLE_FORWARD",
  EGRESS_HOP_ROLE_EXIT = "EGRESS_HOP_ROLE_EXIT",
  EGRESS_HOP_ROLE_CONTROL_PLANE = "EGRESS_HOP_ROLE_CONTROL_PLANE",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum EgressListenerKind {
  EGRESS_LISTENER_KIND_UNSPECIFIED = "EGRESS_LISTENER_KIND_UNSPECIFIED",
  EGRESS_LISTENER_KIND_DIRECT = "EGRESS_LISTENER_KIND_DIRECT",
  EGRESS_LISTENER_KIND_PROVIDER_ROUTE = "EGRESS_LISTENER_KIND_PROVIDER_ROUTE",
  EGRESS_LISTENER_KIND_DYNAMIC_LEASE = "EGRESS_LISTENER_KIND_DYNAMIC_LEASE",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface ProxySelectorPolicy {
  strategy: ProxySelectorStrategy;
  max_fails: number;
  fail_timeout: string | undefined;
}

export interface ProxyProviderDescriptor {
  provider_id: string;
  display_name: string;
  capabilities: ProxyCapability[];
  protocols: ProxyProtocol[];
  min_sticky_ttl: string | undefined;
  max_sticky_ttl: string | undefined;
  upstream_kinds: ProxyUpstreamKind[];
  rotation_modes: ProxyRotationMode[];
}

export interface ProxyProviderAccount {
  account_id: string;
  provider_id: string;
  display_name: string;
  status: ProxyProviderAccountStatus;
  credential_configured: boolean;
  created_at: string | undefined;
  updated_at: string | undefined;
  username: string;
  password_value: string;
}

export interface ProxyFixedSourceDescriptor {
  endpoint_count: number;
  region_codes: string[];
  uri: string;
}

export interface ProxySubscriptionSourceDescriptor {
  url: string;
  interval: string | undefined;
  filter: string;
  exclude_filter: string;
  health_check_url: string;
  health_interval: string | undefined;
  health_timeout: string | undefined;
  health_lazy: boolean;
  expected_status: number;
  region_codes: string[];
}

export interface ProxyAPIPoolSourceDescriptor {
  provider_account_id: string;
  endpoint_count: number;
}

export interface ProxyDynamicIPSourceDescriptor {
  provider_account_id: string;
  requires_account_lease: boolean;
  min_sticky_ttl: string | undefined;
  max_sticky_ttl: string | undefined;
}

export interface ProxySourceDescriptor {
  source_id: string;
  provider_id: string;
  display_name: string;
  kind: ProxySourceKind;
  enabled: boolean;
  capabilities: ProxyCapability[];
  protocols: ProxyProtocol[];
  fixed_proxy?: ProxyFixedSourceDescriptor | undefined;
  subscription?: ProxySubscriptionSourceDescriptor | undefined;
  api_pool?: ProxyAPIPoolSourceDescriptor | undefined;
  dynamic_ip?: ProxyDynamicIPSourceDescriptor | undefined;
}

export interface ProxySourceNode {
  source_id: string;
  node_id: string;
  display_name: string;
  node_type: string;
  status: ProxySourceNodeStatus;
  delay_ms: number;
  checked_at: string | undefined;
  error_message: string;
}

export interface ProxyDynamicGatewayCandidate {
  provider_account_id: string;
  provider_id: string;
  gateway_id: string;
  display_name: string;
  region_codes: string[];
  protocol: ProxyProtocol;
  priority: number;
}

export interface EgressRoutePolicy {
  country_code: string;
  region: string;
  purpose: string;
  strategy: ProxySelectorStrategy;
  max_attempts: number;
  require_dynamic_exit: boolean;
  allow_direct_dynamic_gateway: boolean;
}

export interface EgressRoutePlan {
  route_id: string;
  policy: EgressRoutePolicy | undefined;
  dynamic_gateway: ProxyDynamicGatewayCandidate | undefined;
  selection_reasons: string[];
  planned_at: string | undefined;
  route: EgressRoute | undefined;
}

export interface ProviderControlPlaneAccess {
  uses_proxy: boolean;
  proxy_ref: string;
  protocols: ProxyProtocol[];
}

export interface ProxySessionPolicy {
  mode: ProxySessionMode;
  region: string;
  state: string;
  city: string;
  asn: string;
  sticky_ttl: string | undefined;
  labels: { [key: string]: string };
  upstream_kind: ProxyUpstreamKind;
  rotation_mode: ProxyRotationMode;
}

export interface ProxySessionPolicy_LabelsEntry {
  key: string;
  value: string;
}

export interface ProxySession {
  session_id: string;
  policy: ProxySessionPolicy | undefined;
  created_at: string | undefined;
  expires_at: string | undefined;
  labels: { [key: string]: string };
  provider_id: string;
  egress: ProxyEndpoint | undefined;
  account_id: string;
  purpose: string;
}

export interface ProxySession_LabelsEntry {
  key: string;
  value: string;
}

export interface ProxyEndpoint {
  id: string;
  protocol: ProxyProtocol;
  host: string;
  port: number;
  session_id: string;
  upstream_kind: ProxyUpstreamKind;
  rotation_mode: ProxyRotationMode;
  labels: { [key: string]: string };
  provider_id: string;
}

export interface ProxyEndpoint_LabelsEntry {
  key: string;
  value: string;
}

export interface ProxyDynamicLease {
  lease_id: string;
  account_id: string;
  purpose: string;
  provider_account_id: string;
  status: ProxyDynamicLeaseStatus;
  session: ProxySession | undefined;
  egress: ProxyEndpoint | undefined;
  listener: EgressListener | undefined;
  ip_fraud_check: ProxyIPFraudCheck | undefined;
  edge_access_check: ProxyEdgeAccessCheck | undefined;
  acquired_at: string | undefined;
  expires_at: string | undefined;
  error_message: string;
  route_plan: EgressRoutePlan | undefined;
}

export interface ProxyExitGeo {
  ip: string;
  country_code: string;
  checked_at: string | undefined;
  error_message: string;
  region: string;
  city: string;
}

export interface ProxyExitIP {
  ip: string;
  checked_at: string | undefined;
  error_message: string;
}

export interface ProxyTargetConnectivityCheck {
  target_url: string;
  host: string;
  reachable: boolean;
  status_code: number;
  latency_ms: number;
  checked_at: string | undefined;
  error_message: string;
}

export interface ProxyIPFraudCheck {
  ip: string;
  network_kind: ProxyIPNetworkKind;
  anonymizer_kind: ProxyIPAnonymizerKind;
  risk_level: ProxyIPFraudRiskLevel;
  risk_score: number;
  risk_signals: ProxyIPFraudSignal[];
  country_code: string;
  region: string;
  city: string;
  asn: string;
  organization: string;
  isp: string;
  checked_at: string | undefined;
  error_message: string;
  provider_id: string;
  provider_display_name: string;
}

export interface ProxyEdgeAccessCheck {
  ip: string;
  risk_level: ProxyEdgeAccessRiskLevel;
  risk_score: number;
  risk_signals: ProxyEdgeAccessRiskSignal[];
  ip_fraud_check: ProxyIPFraudCheck | undefined;
  checked_at: string | undefined;
  error_message: string;
}

export interface ProxyEdgeCanarySettings {
  url: string;
  token_secret_ref: SecretRef | undefined;
  clear_token: boolean;
  enabled: boolean;
  token_value: string;
}

export interface ProxyEdgeCanarySettingsView {
  url: string;
  token_configured: boolean;
  enabled: boolean;
}

export interface ProxyIPFraudProviderSettings {
  provider_id: string;
  weight: number;
  kind: ProxyIPFraudProviderKind;
  anonymous: boolean;
  api_key_secret_refs: SecretRef[];
  clear_api_keys: boolean;
  api_key_values: string[];
}

export interface ProxyIPFraudProviderSettingsView {
  provider_id: string;
  weight: number;
  kind: ProxyIPFraudProviderKind;
  anonymous: boolean;
  api_key_configured: boolean;
  api_key_count: number;
}

export interface ProxyIPFraudProviderDescriptor {
  provider_id: string;
  default_weight: number;
  kind: ProxyIPFraudProviderKind;
  supports_anonymous: boolean;
  supports_api_key: boolean;
  display_name: string;
}

export interface ProxyDynamicIPGatewaySettings {
  endpoint_url: string;
}

export interface ProxyDynamicIPProviderSettings {
  provider_id: string;
  gateways: ProxyDynamicIPGatewaySettings[];
}

export interface ProxyRuntimeCheckSettings {
  proxy_exit_ip_timeout: string | undefined;
}

export interface EgressProfileSourceRef {
  source_id: string;
  node_id: string;
}

export interface EgressProfileLineSettings {
  kind: EgressProfileLineKind;
  source: EgressProfileSourceRef | undefined;
  health_check_url: string;
  health_interval: string | undefined;
  health_timeout: string | undefined;
  expected_status: number;
}

export interface EgressProfileExitSettings {
  kind: EgressProfileExitKind;
  source: EgressProfileSourceRef | undefined;
  health_check_url: string;
  health_interval: string | undefined;
  health_timeout: string | undefined;
  expected_status: number;
  dynamic_provider_id: string;
}

export interface EgressProfileSettings {
  profile_id: string;
  display_name: string;
  enabled: boolean;
  line: EgressProfileLineSettings | undefined;
  exit: EgressProfileExitSettings | undefined;
}

export interface ProxyIngressRuleSettings {
  rule_id: string;
  display_name: string;
  enabled: boolean;
  username: string;
  password_value: string;
  profile_id: string;
}

export interface ProxyRuntimeSettings {
  edge_canary: ProxyEdgeCanarySettingsView | undefined;
  ip_fraud_providers: ProxyIPFraudProviderSettingsView[];
  dynamic_ip_providers: ProxyDynamicIPProviderSettings[];
  check_settings: ProxyRuntimeCheckSettings | undefined;
  egress_profiles: EgressProfileSettings[];
  ingress_rules: ProxyIngressRuleSettings[];
}

export interface ProxyRuntimePersistentSettings {
  edge_canary: ProxyEdgeCanarySettings | undefined;
  ip_fraud_providers: ProxyIPFraudProviderSettings[];
  dynamic_ip_providers: ProxyDynamicIPProviderSettings[];
  check_settings: ProxyRuntimeCheckSettings | undefined;
  egress_profiles: EgressProfileSettings[];
  ingress_rules: ProxyIngressRuleSettings[];
}

export interface ProxyRuntimeOverview {
  route_runtime: ProxyRouteRuntimeKind;
  route_runtime_status: string;
  provider_account_count: number;
  source_count: number;
  active_lease_count: number;
  updated_at: string | undefined;
  source_runtime: ProxySourceRuntimeKind;
  source_runtime_status: string;
}

export interface ProxyPoolSnapshot {
  pool_id: string;
  provider_descriptor: ProxyProviderDescriptor | undefined;
  endpoints: ProxyEndpoint[];
  refreshed_at: string | undefined;
  sources: ProxySourceDescriptor[];
  dynamic_leases: ProxyDynamicLease[];
}

export interface EgressListener {
  listener_id: string;
  kind: EgressListenerKind;
  listen_addr: string;
  protocol: ProxyProtocol;
  route_id: string;
  managed: boolean;
  labels: { [key: string]: string };
}

export interface EgressListener_LabelsEntry {
  key: string;
  value: string;
}

export interface EgressHop {
  hop_id: string;
  order: number;
  role: EgressHopRole;
  selector: ProxySelectorPolicy | undefined;
  endpoints: ProxyEndpoint[];
}

export interface EgressRoute {
  route_id: string;
  hops: EgressHop[];
}

export interface EgressGateway {
  gateway_id: string;
  listeners: EgressListener[];
  pool: ProxyPoolSnapshot | undefined;
  data_plane_route: EgressRoute | undefined;
  control_plane_route: EgressRoute | undefined;
  provider_control_plane: ProviderControlPlaneAccess | undefined;
  updated_at: string | undefined;
  overview: ProxyRuntimeOverview | undefined;
}

export interface ListProxyProvidersRequest {
}

export interface ListProxyProvidersResponse {
  providers: ProxyProviderDescriptor[];
}

export interface GetEgressGatewayRequest {
  gateway_id: string;
}

export interface GetEgressGatewayResponse {
  gateway: EgressGateway | undefined;
}

export interface GetProxyPoolRequest {
  pool_id: string;
}

export interface GetProxyPoolResponse {
  pool: ProxyPoolSnapshot | undefined;
}

export interface RefreshProxyPoolRequest {
  pool_id: string;
}

export interface RefreshProxyPoolResponse {
  pool: ProxyPoolSnapshot | undefined;
}

export interface ListProxyProviderAccountsRequest {
}

export interface ListProxyProviderAccountsResponse {
  accounts: ProxyProviderAccount[];
}

export interface UpsertProxyProviderAccountRequest {
  account_id: string;
  provider_id: string;
  display_name: string;
  enabled: boolean;
  username: string;
  password_secret_ref: SecretRef | undefined;
  clear_password: boolean;
  password_value: string;
}

export interface UpsertProxyProviderAccountResponse {
  account: ProxyProviderAccount | undefined;
}

export interface DeleteProxyProviderAccountRequest {
  account_id: string;
}

export interface DeleteProxyProviderAccountResponse {
}

export interface ListProxySourcesRequest {
}

export interface ListProxySourcesResponse {
  sources: ProxySourceDescriptor[];
}

export interface UpsertProxySubscriptionSourceRequest {
  source_id: string;
  display_name: string;
  enabled: boolean;
  url: string;
  clear_url: boolean;
  interval: string | undefined;
  filter: string;
  exclude_filter: string;
  health_check_url: string;
  health_interval: string | undefined;
  health_timeout: string | undefined;
  health_lazy: boolean;
  expected_status: number;
  region_codes: string[];
}

export interface UpsertProxySubscriptionSourceResponse {
  source: ProxySourceDescriptor | undefined;
}

export interface UpsertProxyFixedSourceRequest {
  source_id: string;
  display_name: string;
  enabled: boolean;
  uri: string;
  clear_uri: boolean;
  region_codes: string[];
}

export interface UpsertProxyFixedSourceResponse {
  source: ProxySourceDescriptor | undefined;
}

export interface DeleteProxySourceRequest {
  source_id: string;
}

export interface DeleteProxySourceResponse {
}

export interface ListProxySourceNodesRequest {
  source_id: string;
}

export interface ListProxySourceNodesResponse {
  nodes: ProxySourceNode[];
}

export interface ProxyResourceRef {
  proxy_kind: ProxyKind;
  source_id: string;
  node_id: string;
  display_name: string;
  source_kind: ProxySourceKind;
  region_codes: string[];
}

export interface ProxyNodeObservation {
  status: ProxySourceNodeStatus;
  delay_ms: number;
  exit_ip: string;
  exit_geo: ProxyExitGeo | undefined;
  ip_fraud_check: ProxyIPFraudCheck | undefined;
  observed_at: string | undefined;
  expires_at: string | undefined;
  error_message: string;
}

export interface ResolveProxyRequest {
  proxy_kind: ProxyKind;
  country_code: string;
  region: string;
  purpose: string;
  target_host: string;
  target_port: number;
  stickiness_key: string;
  ttl: string | undefined;
  force_new: boolean;
  strategy: ProxySelectorStrategy;
}

export interface ResolvedProxy {
  proxy_url: string;
  endpoint: ProxyEndpoint | undefined;
  proxy_kind: ProxyKind;
  resource: ProxyResourceRef | undefined;
  assignment_id: string;
  lease_id: string;
  expires_at: string | undefined;
  observation: ProxyNodeObservation | undefined;
  route_plan: EgressRoutePlan | undefined;
}

export interface ResolveProxyResponse {
  proxy: ResolvedProxy | undefined;
  candidates: ProxyResourceRef[];
}

export interface ListProxyDynamicLeasesRequest {
}

export interface ListProxyDynamicLeasesResponse {
  leases: ProxyDynamicLease[];
}

export interface AcquireProxyLeaseRequest {
  account_id: string;
  purpose: string;
  policy: ProxySessionPolicy | undefined;
  force_new: boolean;
  route_policy: EgressRoutePolicy | undefined;
}

export interface AcquireProxyLeaseResponse {
  lease: ProxyDynamicLease | undefined;
  pool: ProxyPoolSnapshot | undefined;
  egress: ProxyEndpoint | undefined;
  route_plan: EgressRoutePlan | undefined;
}

export interface ReleaseProxyLeaseRequest {
  lease_id: string;
  account_id: string;
  purpose: string;
}

export interface ReleaseProxyLeaseResponse {
  lease: ProxyDynamicLease | undefined;
}

export interface GetProxyExitIPRequest {
  pool_id: string;
  provider_id: string;
  listener_id: string;
}

export interface GetProxyExitIPResponse {
  proxy_exit_ip: ProxyExitIP | undefined;
}

export interface GetProxyExitGeoRequest {
  ip: string;
}

export interface GetProxyExitGeoResponse {
  proxy_exit_geo: ProxyExitGeo | undefined;
}

export interface CheckProxyIPFraudRequest {
  ip: string;
}

export interface CheckProxyIPFraudResponse {
  check: ProxyIPFraudCheck | undefined;
}

export interface CheckProxyEdgeAccessRequest {
  pool_id: string;
  provider_id: string;
  listener_id: string;
  expected_country_code: string;
  ip: string;
}

export interface CheckProxyEdgeAccessResponse {
  check: ProxyEdgeAccessCheck | undefined;
}

export interface CheckProxyTargetConnectivityRequest {
  pool_id: string;
  provider_id: string;
  listener_id: string;
  target_url: string;
}

export interface CheckProxyTargetConnectivityResponse {
  check: ProxyTargetConnectivityCheck | undefined;
}

export interface GetProxyRuntimeSettingsRequest {
}

export interface GetProxyRuntimeSettingsResponse {
  settings: ProxyRuntimeSettings | undefined;
}

export interface ListProxyIPFraudProvidersRequest {
}

export interface ListProxyIPFraudProvidersResponse {
  providers: ProxyIPFraudProviderDescriptor[];
}

export interface UpdateProxyRuntimeSettingsRequest {
  edge_canary: ProxyEdgeCanarySettings | undefined;
  ip_fraud_providers: ProxyIPFraudProviderSettings[];
  dynamic_ip_providers: ProxyDynamicIPProviderSettings[];
  check_settings: ProxyRuntimeCheckSettings | undefined;
  egress_profiles: EgressProfileSettings[];
  ingress_rules: ProxyIngressRuleSettings[];
}

export interface UpdateProxyRuntimeSettingsResponse {
  settings: ProxyRuntimeSettings | undefined;
}

export interface UpdateProxyEgressProfilesRequest {
  egress_profiles: EgressProfileSettings[];
}

export interface UpdateProxyEgressProfilesResponse {
  settings: ProxyRuntimeSettings | undefined;
}

export interface UpdateProxyIngressRulesRequest {
  ingress_rules: ProxyIngressRuleSettings[];
}

export interface UpdateProxyIngressRulesResponse {
  settings: ProxyRuntimeSettings | undefined;
}
