// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: byte/v/forge/contracts/wa/v1/wa.proto

/* eslint-disable */
import type { EventContext } from "../../common/v1/common";

export const protobufPackage = "byte.v.forge.contracts.wa.v1";

export enum WaOtpSource {
  WA_OTP_SOURCE_UNSPECIFIED = "WA_OTP_SOURCE_UNSPECIFIED",
  WA_OTP_SOURCE_LONG_CONNECTION = "WA_OTP_SOURCE_LONG_CONNECTION",
  WA_OTP_SOURCE_AUTO_EXTRACTION = "WA_OTP_SOURCE_AUTO_EXTRACTION",
  WA_OTP_SOURCE_IMPORTED_HISTORY = "WA_OTP_SOURCE_IMPORTED_HISTORY",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface WaOtpReceivedEvent {
  context: EventContext | undefined;
  workspace_id: string;
  e164_number: string;
  source: WaOtpSource;
  otp: string;
  wa_account_id: string;
  client_profile_id: string;
  registered_identity_id: string;
  message_id: string;
  candidate_id: string;
  received_at: string | undefined;
  source_party: string;
}
