// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: byte/v/forge/contracts/common/v1/common.proto

/* eslint-disable */

export const protobufPackage = "byte.v.forge.contracts.common.v1";

export interface EventContext {
  event_id: string;
  event_name: string;
  event_version: string;
  occurred_at: string | undefined;
  source_service: string;
  correlation_id: string;
  trace_id: string;
  idempotency_key: string;
}
