// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: byte/v/forge/contracts/common/v1/common.proto

/* eslint-disable */

export const protobufPackage = "byte.v.forge.contracts.common.v1";

export interface EventMetadata {
  id: string;
  type: string;
  version: string;
  time: string | undefined;
  source: string;
  correlation_id: string;
  trace_id: string;
  idempotency_key: string;
  subject: string;
  spec_version: string;
  data_content_type: string;
  data_schema: string;
}

export interface SecretRef {
  secret_id: string;
  provider: string;
  purpose: string;
  expires_at: string | undefined;
}

export interface ArtifactRef {
  artifact_id: string;
  uri: string;
  content_type: string;
  size_bytes: number;
  purpose: string;
  expires_at: string | undefined;
}

export interface OperationError {
  code: string;
  message: string;
  retryable: boolean;
  retry_after: string | undefined;
}
