// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: byte/v/forge/contracts/common/v1/eventbus.proto

/* eslint-disable */
import type { EventContext } from "./common";

export const protobufPackage = "byte.v.forge.contracts.common.v1";

export interface EventEnvelope {
  context: EventContext | undefined;
  subject: string;
  proto_type: string;
  payload: Uint8Array;
  content_type: string;
  attributes: { [key: string]: string };
}

export interface EventEnvelope_AttributesEntry {
  key: string;
  value: string;
}

export interface EventPublishAck {
  stream: string;
  sequence: number;
  duplicate: boolean;
}

export interface DeadLetterEvent {
  context: EventContext | undefined;
  original_subject: string;
  original_event_id: string;
  original_event_name: string;
  original_event_version: string;
  original_source_service: string;
  consumer_durable: string;
  delivery_attempt: number;
  error_code: string;
  error_message: string;
  correlation_id: string;
}
