// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: byte/v/forge/contracts/common/v1/eventbus.proto

/* eslint-disable */
import type { EventMetadata } from "./common";

export const protobufPackage = "byte.v.forge.contracts.common.v1";

export enum EventKind {
  EVENT_KIND_UNSPECIFIED = "EVENT_KIND_UNSPECIFIED",
  EVENT_KIND_FACT = "EVENT_KIND_FACT",
  EVENT_KIND_COMMAND = "EVENT_KIND_COMMAND",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface EventEnvelope {
  metadata: EventMetadata | undefined;
  subject: string;
  payload_type: string;
  payload: Uint8Array;
  data_content_type: string;
  extensions: { [key: string]: string };
}

export interface EventEnvelope_ExtensionsEntry {
  key: string;
  value: string;
}

export interface EventDefinition {
  subject: string;
  event_name: string;
  event_version: string;
  kind: EventKind;
  payload_type: string;
  owner_service: string;
  consumer_durable: string;
  retryable: boolean;
  max_deliveries: number;
  retry_delay_seconds: number;
}

export interface EventCatalog {
  stream_name: string;
  stream_subject: string;
  definitions: EventDefinition[];
}

export interface EventPublishAck {
  stream: string;
  sequence: number;
  duplicate: boolean;
}

export interface DeadLetterEvent {
  metadata: EventMetadata | undefined;
  original_subject: string;
  original_event_id: string;
  original_event_type: string;
  original_event_version: string;
  original_source: string;
  consumer_durable: string;
  delivery_attempt: number;
  error_code: string;
  error_message: string;
  correlation_id: string;
}
