// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: byte/v/forge/contracts/account/v1/account.proto

/* eslint-disable */
import type { EventMetadata } from "../../common/v1/common";

export const protobufPackage = "byte.v.forge.contracts.account.v1";

export enum AccountActionTone {
  ACCOUNT_ACTION_TONE_UNSPECIFIED = "ACCOUNT_ACTION_TONE_UNSPECIFIED",
  ACCOUNT_ACTION_TONE_DEFAULT = "ACCOUNT_ACTION_TONE_DEFAULT",
  ACCOUNT_ACTION_TONE_PRIMARY = "ACCOUNT_ACTION_TONE_PRIMARY",
  ACCOUNT_ACTION_TONE_DANGER = "ACCOUNT_ACTION_TONE_DANGER",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum AccountActionEngine {
  ACCOUNT_ACTION_ENGINE_UNSPECIFIED = "ACCOUNT_ACTION_ENGINE_UNSPECIFIED",
  ACCOUNT_ACTION_ENGINE_N8N = "ACCOUNT_ACTION_ENGINE_N8N",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum AccountActionAPIKind {
  ACCOUNT_ACTION_API_KIND_UNSPECIFIED = "ACCOUNT_ACTION_API_KIND_UNSPECIFIED",
  ACCOUNT_ACTION_API_KIND_TYPED = "ACCOUNT_ACTION_API_KIND_TYPED",
  ACCOUNT_ACTION_API_KIND_RAW_N8N = "ACCOUNT_ACTION_API_KIND_RAW_N8N",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum AccountChangeKind {
  ACCOUNT_CHANGE_KIND_UNSPECIFIED = "ACCOUNT_CHANGE_KIND_UNSPECIFIED",
  ACCOUNT_CHANGE_KIND_UPSERTED = "ACCOUNT_CHANGE_KIND_UPSERTED",
  ACCOUNT_CHANGE_KIND_UPDATED = "ACCOUNT_CHANGE_KIND_UPDATED",
  ACCOUNT_CHANGE_KIND_DELETED = "ACCOUNT_CHANGE_KIND_DELETED",
  ACCOUNT_CHANGE_KIND_STATUS_CHANGED = "ACCOUNT_CHANGE_KIND_STATUS_CHANGED",
  ACCOUNT_CHANGE_KIND_CREDENTIAL_CHANGED = "ACCOUNT_CHANGE_KIND_CREDENTIAL_CHANGED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface AccountKey {
  source_service: string;
  account_type: string;
  account_id: string;
}

export interface AccountSubject {
  email?: string | undefined;
  phone_e164?: string | undefined;
  external_id?: string | undefined;
  display: string;
}

export interface AccountError {
  code: string;
  message: string;
  retryable: boolean;
}

export interface AccountStatus {
  value: string;
  label: string;
  error: AccountError | undefined;
}

export interface AccountCredentialState {
  kind: string;
  present: boolean;
  status: string;
  expires_at: string | undefined;
  updated_at: string | undefined;
}

export interface Account {
  key: AccountKey | undefined;
  provider_key: string;
  display_name: string;
  subject: AccountSubject | undefined;
  status: AccountStatus | undefined;
  credential_states: AccountCredentialState[];
  created_at: string | undefined;
  updated_at: string | undefined;
}

export interface AccountActionDescriptor {
  action_id: string;
  label: string;
  tone: AccountActionTone;
  disabled: boolean;
  disabled_reason: string;
  requires_confirmation: boolean;
}

export interface AccountActionButton {
  id: string;
  label: string;
  placement: string;
  intent: string;
  start_path: string;
}

export interface AccountActionWorkflowDefinition {
  key: string;
  id_prefix: string;
  start_path: string;
  n8n_action_scope: string;
  n8n_webhook_path: string;
  action_path_prefix: string;
  action_api_kind: AccountActionAPIKind;
}

export interface AccountActionDefinition {
  action_id: string;
  display_name: string;
  owner: string;
  engine: AccountActionEngine;
  request_proto: string;
  response_proto: string;
  required_account_statuses: string[];
  blocked_account_statuses: string[];
  required_fields: string[];
  capabilities: string[];
  visibility: string;
  workflow: AccountActionWorkflowDefinition | undefined;
  ui_buttons: AccountActionButton[];
}

export interface AccountActionCatalog {
  actions: AccountActionDefinition[];
}

export interface AccountChangedEvent {
  metadata: EventMetadata | undefined;
  change_kind: AccountChangeKind;
  account: Account | undefined;
}
