// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: byte/v/forge/contracts/sms/v1/sms.proto

/* eslint-disable */
import type { EventMetadata, SecretRef } from "../../common/v1/common";

export const protobufPackage = "byte.v.forge.contracts.sms.v1";

export enum SmsOrderStatus {
  SMS_ORDER_STATUS_UNSPECIFIED = "SMS_ORDER_STATUS_UNSPECIFIED",
  SMS_ORDER_STATUS_PENDING_CODE = "SMS_ORDER_STATUS_PENDING_CODE",
  SMS_ORDER_STATUS_MESSAGE_SENT = "SMS_ORDER_STATUS_MESSAGE_SENT",
  SMS_ORDER_STATUS_CODE_RECEIVED = "SMS_ORDER_STATUS_CODE_RECEIVED",
  SMS_ORDER_STATUS_ADDITIONAL_CODE_REQUESTED = "SMS_ORDER_STATUS_ADDITIONAL_CODE_REQUESTED",
  SMS_ORDER_STATUS_COMPLETED = "SMS_ORDER_STATUS_COMPLETED",
  SMS_ORDER_STATUS_CANCELED = "SMS_ORDER_STATUS_CANCELED",
  SMS_ORDER_STATUS_EXPIRED = "SMS_ORDER_STATUS_EXPIRED",
  SMS_ORDER_STATUS_FAILED = "SMS_ORDER_STATUS_FAILED",
  SMS_ORDER_STATUS_ACQUIRE_REQUESTED = "SMS_ORDER_STATUS_ACQUIRE_REQUESTED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum SmsErrorCode {
  SMS_ERROR_CODE_UNSPECIFIED = "SMS_ERROR_CODE_UNSPECIFIED",
  SMS_ERROR_CODE_VALIDATION_FAILED = "SMS_ERROR_CODE_VALIDATION_FAILED",
  SMS_ERROR_CODE_ROUTE_NOT_FOUND = "SMS_ERROR_CODE_ROUTE_NOT_FOUND",
  SMS_ERROR_CODE_ORDER_NOT_FOUND = "SMS_ERROR_CODE_ORDER_NOT_FOUND",
  SMS_ERROR_CODE_ORDER_ALREADY_FINALIZED = "SMS_ERROR_CODE_ORDER_ALREADY_FINALIZED",
  SMS_ERROR_CODE_NO_NUMBER_AVAILABLE = "SMS_ERROR_CODE_NO_NUMBER_AVAILABLE",
  SMS_ERROR_CODE_RATE_LIMITED = "SMS_ERROR_CODE_RATE_LIMITED",
  SMS_ERROR_CODE_SUPPLY_UNAVAILABLE = "SMS_ERROR_CODE_SUPPLY_UNAVAILABLE",
  SMS_ERROR_CODE_UPSTREAM_REJECTED = "SMS_ERROR_CODE_UPSTREAM_REJECTED",
  SMS_ERROR_CODE_TIMEOUT = "SMS_ERROR_CODE_TIMEOUT",
  SMS_ERROR_CODE_UNSUPPORTED_OPERATION = "SMS_ERROR_CODE_UNSUPPORTED_OPERATION",
  SMS_ERROR_CODE_ORDER_EXPIRED = "SMS_ERROR_CODE_ORDER_EXPIRED",
  SMS_ERROR_CODE_CANCEL_NOT_ALLOWED = "SMS_ERROR_CODE_CANCEL_NOT_ALLOWED",
  SMS_ERROR_CODE_INSUFFICIENT_BALANCE = "SMS_ERROR_CODE_INSUFFICIENT_BALANCE",
  SMS_ERROR_CODE_INTERNAL = "SMS_ERROR_CODE_INTERNAL",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum SmsRouteStrategy {
  SMS_ROUTE_STRATEGY_UNSPECIFIED = "SMS_ROUTE_STRATEGY_UNSPECIFIED",
  SMS_ROUTE_STRATEGY_BALANCED = "SMS_ROUTE_STRATEGY_BALANCED",
  SMS_ROUTE_STRATEGY_LOWEST_PRICE = "SMS_ROUTE_STRATEGY_LOWEST_PRICE",
  SMS_ROUTE_STRATEGY_MOST_AVAILABLE = "SMS_ROUTE_STRATEGY_MOST_AVAILABLE",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface SmsError {
  code: SmsErrorCode;
  message: string;
  retryable: boolean;
}

export interface DecimalMoney {
  currency_code: string;
  amount_decimal: string;
}

export interface PhoneNumber {
  e164_number: string;
  national_number: string;
  country_iso2: string;
  country_calling_code: string;
}

export interface SmsTarget {
  application_key: string;
  country_iso2: string;
  country_calling_code: string;
}

export interface SmsOfferRef {
  offer_id: string;
  provider_key: string;
  target: SmsTarget | undefined;
}

export interface SmsNumberAcquireParams {
  offer_ref: SmsOfferRef | undefined;
  application_key: string;
  country_iso2: string;
  country_calling_code: string;
  min_available_count: number;
  route_failure_policy: SmsRouteFailurePolicy | undefined;
  max_price: DecimalMoney | undefined;
  min_price: DecimalMoney | undefined;
}

export interface SmsCode {
  secret_ref: SecretRef | undefined;
  received_at: string | undefined;
}

export interface SmsOrder {
  order_id: string;
  request_id: string;
  target: SmsTarget | undefined;
  phone_number: PhoneNumber | undefined;
  status: SmsOrderStatus;
  price: DecimalMoney | undefined;
  acquired_at: string | undefined;
  expires_at: string | undefined;
  updated_at: string | undefined;
  last_error: SmsError | undefined;
  can_request_additional_code: boolean;
  cancel_allowed_at: string | undefined;
}

export interface AcquireNumberRequest {
  request_id: string;
  lease_duration: string | undefined;
  acquire_params: SmsNumberAcquireParams | undefined;
}

export interface AcquireNumberResponse {
  order: SmsOrder | undefined;
  error: SmsError | undefined;
}

export interface GetOrderRequest {
  order_id: string;
}

export interface GetOrderResponse {
  order: SmsOrder | undefined;
  error: SmsError | undefined;
}

export interface MarkMessageSentRequest {
  order_id: string;
  request_id: string;
}

export interface RequestAdditionalCodeRequest {
  order_id: string;
  request_id: string;
}

export interface CompleteOrderRequest {
  order_id: string;
  request_id: string;
}

export interface CancelOrderRequest {
  order_id: string;
  request_id: string;
  reason: string;
}

export interface MarkMessageSentResponse {
  order: SmsOrder | undefined;
  error: SmsError | undefined;
}

export interface RequestAdditionalCodeResponse {
  order: SmsOrder | undefined;
  error: SmsError | undefined;
}

export interface CompleteOrderResponse {
  order: SmsOrder | undefined;
  error: SmsError | undefined;
}

export interface CancelOrderResponse {
  order: SmsOrder | undefined;
  error: SmsError | undefined;
}

export interface SmsApplicationInfo {
  application_key: string;
  display_name: string;
}

export interface SmsCountry {
  country_iso2: string;
  name: string;
  country_calling_code: string;
}

export interface SmsPriceOffer {
  application_key: string;
  application_name: string;
  country_iso2: string;
  country_name: string;
  country_calling_code: string;
  price: DecimalMoney | undefined;
  available_count: number;
  provider_key: string;
  provider_display_name: string;
  supports_cancel: boolean;
  supports_additional_code: boolean;
  requires_mark_message_sent: boolean;
  observed_at: string | undefined;
  offer_ref: SmsOfferRef | undefined;
}

export interface SmsRoutePolicy {
  strategy: SmsRouteStrategy;
  max_price: DecimalMoney | undefined;
  limit: number;
  min_available_count: number;
  failure_policy: SmsRouteFailurePolicy | undefined;
  min_price: DecimalMoney | undefined;
}

export interface SmsRouteFailurePolicy {
  scope_key: string;
  failure_threshold: number;
  failure_window_seconds: number;
  disable_ttl_seconds: number;
}

export interface RecommendSmsRoutesRequest {
  target: SmsTarget | undefined;
  policy: SmsRoutePolicy | undefined;
  provider_keys: string[];
}

export interface SmsRouteRecommendation {
  offer: SmsPriceOffer | undefined;
  score: number;
}

export interface RecommendSmsRoutesResponse {
  recommendations: SmsRouteRecommendation[];
  error: SmsError | undefined;
}

export interface SmsProviderInfo {
  provider_key: string;
  display_name: string;
  supports_balance: boolean;
  supports_catalog: boolean;
  supports_additional_code: boolean;
  requires_mark_message_sent: boolean;
}

export interface ListSmsProvidersRequest {
}

export interface ListSmsProvidersResponse {
  providers: SmsProviderInfo[];
  error: SmsError | undefined;
}

export interface ListSmsApplicationsRequest {
  provider_key: string;
}

export interface ListSmsApplicationsResponse {
  applications: SmsApplicationInfo[];
  error: SmsError | undefined;
}

export interface ListSmsCountriesRequest {
  provider_key: string;
}

export interface ListSmsCountriesResponse {
  countries: SmsCountry[];
  error: SmsError | undefined;
}

export interface ListSmsPriceOffersRequest {
  application_key: string;
  country_iso2: string;
  country_calling_code: string;
  provider_key: string;
}

export interface ListSmsPriceOffersResponse {
  offers: SmsPriceOffer[];
  error: SmsError | undefined;
}

export interface SmsOrderAcquiredEvent {
  metadata: EventMetadata | undefined;
  order: SmsOrder | undefined;
}

export interface SmsCodeReceivedEvent {
  metadata: EventMetadata | undefined;
  order_id: string;
  code: SmsCode | undefined;
}

export interface SmsOrderStatusChangedEvent {
  metadata: EventMetadata | undefined;
  order_id: string;
  previous_status: SmsOrderStatus;
  current_status: SmsOrderStatus;
  error: SmsError | undefined;
}
