// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: byte/v/forge/contracts/browserautomation/v1/browser_automation.proto

/* eslint-disable */
import type { ArtifactRef, EventMetadata, SecretRef } from "../../common/v1/common";

export const protobufPackage = "byte.v.forge.contracts.browserautomation.v1";

export enum BrowserAutomationErrorCode {
  BROWSER_AUTOMATION_ERROR_CODE_UNSPECIFIED = "BROWSER_AUTOMATION_ERROR_CODE_UNSPECIFIED",
  BROWSER_AUTOMATION_ERROR_CODE_VALIDATION_FAILED = "BROWSER_AUTOMATION_ERROR_CODE_VALIDATION_FAILED",
  BROWSER_AUTOMATION_ERROR_CODE_SESSION_NOT_FOUND = "BROWSER_AUTOMATION_ERROR_CODE_SESSION_NOT_FOUND",
  BROWSER_AUTOMATION_ERROR_CODE_TASK_NOT_FOUND = "BROWSER_AUTOMATION_ERROR_CODE_TASK_NOT_FOUND",
  BROWSER_AUTOMATION_ERROR_CODE_ARTIFACT_NOT_FOUND = "BROWSER_AUTOMATION_ERROR_CODE_ARTIFACT_NOT_FOUND",
  BROWSER_AUTOMATION_ERROR_CODE_SESSION_ALREADY_FINALIZED = "BROWSER_AUTOMATION_ERROR_CODE_SESSION_ALREADY_FINALIZED",
  BROWSER_AUTOMATION_ERROR_CODE_TASK_ALREADY_FINALIZED = "BROWSER_AUTOMATION_ERROR_CODE_TASK_ALREADY_FINALIZED",
  BROWSER_AUTOMATION_ERROR_CODE_CAPACITY_UNAVAILABLE = "BROWSER_AUTOMATION_ERROR_CODE_CAPACITY_UNAVAILABLE",
  BROWSER_AUTOMATION_ERROR_CODE_BROWSER_UNAVAILABLE = "BROWSER_AUTOMATION_ERROR_CODE_BROWSER_UNAVAILABLE",
  BROWSER_AUTOMATION_ERROR_CODE_PROXY_FAILED = "BROWSER_AUTOMATION_ERROR_CODE_PROXY_FAILED",
  BROWSER_AUTOMATION_ERROR_CODE_NAVIGATION_FAILED = "BROWSER_AUTOMATION_ERROR_CODE_NAVIGATION_FAILED",
  BROWSER_AUTOMATION_ERROR_CODE_SCRIPT_FAILED = "BROWSER_AUTOMATION_ERROR_CODE_SCRIPT_FAILED",
  BROWSER_AUTOMATION_ERROR_CODE_TIMEOUT = "BROWSER_AUTOMATION_ERROR_CODE_TIMEOUT",
  BROWSER_AUTOMATION_ERROR_CODE_UNSUPPORTED_OPERATION = "BROWSER_AUTOMATION_ERROR_CODE_UNSUPPORTED_OPERATION",
  BROWSER_AUTOMATION_ERROR_CODE_INTERNAL = "BROWSER_AUTOMATION_ERROR_CODE_INTERNAL",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum BrowserKind {
  BROWSER_KIND_UNSPECIFIED = "BROWSER_KIND_UNSPECIFIED",
  BROWSER_KIND_CHROMIUM = "BROWSER_KIND_CHROMIUM",
  BROWSER_KIND_FIREFOX = "BROWSER_KIND_FIREFOX",
  BROWSER_KIND_WEBKIT = "BROWSER_KIND_WEBKIT",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum BrowserSessionStatus {
  BROWSER_SESSION_STATUS_UNSPECIFIED = "BROWSER_SESSION_STATUS_UNSPECIFIED",
  BROWSER_SESSION_STATUS_STARTING = "BROWSER_SESSION_STATUS_STARTING",
  BROWSER_SESSION_STATUS_RUNNING = "BROWSER_SESSION_STATUS_RUNNING",
  BROWSER_SESSION_STATUS_STOPPING = "BROWSER_SESSION_STATUS_STOPPING",
  BROWSER_SESSION_STATUS_STOPPED = "BROWSER_SESSION_STATUS_STOPPED",
  BROWSER_SESSION_STATUS_FAILED = "BROWSER_SESSION_STATUS_FAILED",
  BROWSER_SESSION_STATUS_EXPIRED = "BROWSER_SESSION_STATUS_EXPIRED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum BrowserTaskStatus {
  BROWSER_TASK_STATUS_UNSPECIFIED = "BROWSER_TASK_STATUS_UNSPECIFIED",
  BROWSER_TASK_STATUS_QUEUED = "BROWSER_TASK_STATUS_QUEUED",
  BROWSER_TASK_STATUS_RUNNING = "BROWSER_TASK_STATUS_RUNNING",
  BROWSER_TASK_STATUS_SUCCEEDED = "BROWSER_TASK_STATUS_SUCCEEDED",
  BROWSER_TASK_STATUS_FAILED = "BROWSER_TASK_STATUS_FAILED",
  BROWSER_TASK_STATUS_CANCELED = "BROWSER_TASK_STATUS_CANCELED",
  BROWSER_TASK_STATUS_TIMEOUT = "BROWSER_TASK_STATUS_TIMEOUT",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum BrowserCommandStatus {
  BROWSER_COMMAND_STATUS_UNSPECIFIED = "BROWSER_COMMAND_STATUS_UNSPECIFIED",
  BROWSER_COMMAND_STATUS_SUCCEEDED = "BROWSER_COMMAND_STATUS_SUCCEEDED",
  BROWSER_COMMAND_STATUS_FAILED = "BROWSER_COMMAND_STATUS_FAILED",
  BROWSER_COMMAND_STATUS_TIMEOUT = "BROWSER_COMMAND_STATUS_TIMEOUT",
  BROWSER_COMMAND_STATUS_SKIPPED = "BROWSER_COMMAND_STATUS_SKIPPED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum BrowserSelectorKind {
  BROWSER_SELECTOR_KIND_UNSPECIFIED = "BROWSER_SELECTOR_KIND_UNSPECIFIED",
  BROWSER_SELECTOR_KIND_CSS = "BROWSER_SELECTOR_KIND_CSS",
  BROWSER_SELECTOR_KIND_TEXT = "BROWSER_SELECTOR_KIND_TEXT",
  BROWSER_SELECTOR_KIND_ROLE = "BROWSER_SELECTOR_KIND_ROLE",
  BROWSER_SELECTOR_KIND_LABEL = "BROWSER_SELECTOR_KIND_LABEL",
  BROWSER_SELECTOR_KIND_PLACEHOLDER = "BROWSER_SELECTOR_KIND_PLACEHOLDER",
  BROWSER_SELECTOR_KIND_TEST_ID = "BROWSER_SELECTOR_KIND_TEST_ID",
  BROWSER_SELECTOR_KIND_XPATH = "BROWSER_SELECTOR_KIND_XPATH",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum BrowserSelectorState {
  BROWSER_SELECTOR_STATE_UNSPECIFIED = "BROWSER_SELECTOR_STATE_UNSPECIFIED",
  BROWSER_SELECTOR_STATE_ATTACHED = "BROWSER_SELECTOR_STATE_ATTACHED",
  BROWSER_SELECTOR_STATE_DETACHED = "BROWSER_SELECTOR_STATE_DETACHED",
  BROWSER_SELECTOR_STATE_VISIBLE = "BROWSER_SELECTOR_STATE_VISIBLE",
  BROWSER_SELECTOR_STATE_HIDDEN = "BROWSER_SELECTOR_STATE_HIDDEN",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum BrowserNavigationWaitUntil {
  BROWSER_NAVIGATION_WAIT_UNTIL_UNSPECIFIED = "BROWSER_NAVIGATION_WAIT_UNTIL_UNSPECIFIED",
  BROWSER_NAVIGATION_WAIT_UNTIL_LOAD = "BROWSER_NAVIGATION_WAIT_UNTIL_LOAD",
  BROWSER_NAVIGATION_WAIT_UNTIL_DOM_CONTENT_LOADED = "BROWSER_NAVIGATION_WAIT_UNTIL_DOM_CONTENT_LOADED",
  BROWSER_NAVIGATION_WAIT_UNTIL_NETWORK_IDLE = "BROWSER_NAVIGATION_WAIT_UNTIL_NETWORK_IDLE",
  BROWSER_NAVIGATION_WAIT_UNTIL_COMMIT = "BROWSER_NAVIGATION_WAIT_UNTIL_COMMIT",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum BrowserLoadState {
  BROWSER_LOAD_STATE_UNSPECIFIED = "BROWSER_LOAD_STATE_UNSPECIFIED",
  BROWSER_LOAD_STATE_LOAD = "BROWSER_LOAD_STATE_LOAD",
  BROWSER_LOAD_STATE_DOM_CONTENT_LOADED = "BROWSER_LOAD_STATE_DOM_CONTENT_LOADED",
  BROWSER_LOAD_STATE_NETWORK_IDLE = "BROWSER_LOAD_STATE_NETWORK_IDLE",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum BrowserMouseButton {
  BROWSER_MOUSE_BUTTON_UNSPECIFIED = "BROWSER_MOUSE_BUTTON_UNSPECIFIED",
  BROWSER_MOUSE_BUTTON_LEFT = "BROWSER_MOUSE_BUTTON_LEFT",
  BROWSER_MOUSE_BUTTON_RIGHT = "BROWSER_MOUSE_BUTTON_RIGHT",
  BROWSER_MOUSE_BUTTON_MIDDLE = "BROWSER_MOUSE_BUTTON_MIDDLE",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum BrowserArtifactKind {
  BROWSER_ARTIFACT_KIND_UNSPECIFIED = "BROWSER_ARTIFACT_KIND_UNSPECIFIED",
  BROWSER_ARTIFACT_KIND_SCREENSHOT = "BROWSER_ARTIFACT_KIND_SCREENSHOT",
  BROWSER_ARTIFACT_KIND_VIDEO = "BROWSER_ARTIFACT_KIND_VIDEO",
  BROWSER_ARTIFACT_KIND_TRACE = "BROWSER_ARTIFACT_KIND_TRACE",
  BROWSER_ARTIFACT_KIND_HAR = "BROWSER_ARTIFACT_KIND_HAR",
  BROWSER_ARTIFACT_KIND_CONSOLE_LOG = "BROWSER_ARTIFACT_KIND_CONSOLE_LOG",
  BROWSER_ARTIFACT_KIND_NETWORK_LOG = "BROWSER_ARTIFACT_KIND_NETWORK_LOG",
  BROWSER_ARTIFACT_KIND_DOWNLOAD = "BROWSER_ARTIFACT_KIND_DOWNLOAD",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface BrowserAutomationError {
  code: BrowserAutomationErrorCode;
  message: string;
  retryable: boolean;
}

export interface BrowserViewport {
  width: number;
  height: number;
  device_scale_factor: number;
  mobile: boolean;
}

export interface BrowserProfile {
  browser_kind: BrowserKind;
  locale: string;
  timezone: string;
  user_agent: string;
  viewport: BrowserViewport | undefined;
  proxy_ref: string;
  storage_state_secret_ref: SecretRef | undefined;
  extra_http_headers: { [key: string]: string };
  init_scripts: string[];
}

export interface BrowserProfile_ExtraHttpHeadersEntry {
  key: string;
  value: string;
}

export interface BrowserArtifact {
  artifact_id: string;
  kind: BrowserArtifactKind;
  ref: ArtifactRef | undefined;
  content_type: string;
  size_bytes: number;
  labels: { [key: string]: string };
  created_at: string | undefined;
}

export interface BrowserArtifact_LabelsEntry {
  key: string;
  value: string;
}

export interface BrowserSecurityPolicy {
  allowed_hosts: string[];
  allow_file_upload: boolean;
  allow_cookie_read: boolean;
  allow_storage_state_read: boolean;
  allow_main_world_eval: boolean;
}

export interface BrowserSelector {
  kind: BrowserSelectorKind;
  value: string;
  role_name: string;
  exact: boolean;
  timeout: string | undefined;
}

export interface BrowserSelectorGroup {
  selectors: BrowserSelector[];
  require_all: boolean;
  timeout: string | undefined;
}

export interface BrowserPoint {
  x: number;
  y: number;
}

export interface BrowserRect {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface NavigateCommand {
  url: string;
  wait_until: BrowserNavigationWaitUntil;
  timeout: string | undefined;
}

export interface ReloadCommand {
  wait_until: BrowserNavigationWaitUntil;
  timeout: string | undefined;
}

export interface GoBackCommand {
  wait_until: BrowserNavigationWaitUntil;
  timeout: string | undefined;
}

export interface GoForwardCommand {
  wait_until: BrowserNavigationWaitUntil;
  timeout: string | undefined;
}

export interface ClickCommand {
  selector: BrowserSelector | undefined;
  click_count: number;
  force: boolean;
  timeout: string | undefined;
  selector_group: BrowserSelectorGroup | undefined;
  button: BrowserMouseButton;
  position: BrowserPoint | undefined;
  delay: string | undefined;
  hold_duration: string | undefined;
}

export interface FillCommand {
  selector: BrowserSelector | undefined;
  value: string;
  timeout: string | undefined;
  selector_group: BrowserSelectorGroup | undefined;
}

export interface SetCheckedCommand {
  selector: BrowserSelector | undefined;
  checked: boolean;
  force: boolean;
  timeout: string | undefined;
  selector_group: BrowserSelectorGroup | undefined;
}

export interface TypeTextCommand {
  selector: BrowserSelector | undefined;
  text: string;
  delay: string | undefined;
  timeout: string | undefined;
  selector_group: BrowserSelectorGroup | undefined;
  clear_before: boolean;
}

export interface ClearCommand {
  selector: BrowserSelector | undefined;
  timeout: string | undefined;
  selector_group: BrowserSelectorGroup | undefined;
}

export interface PressCommand {
  selector: BrowserSelector | undefined;
  key: string;
  timeout: string | undefined;
  selector_group: BrowserSelectorGroup | undefined;
}

export interface FocusCommand {
  selector: BrowserSelector | undefined;
  timeout: string | undefined;
  selector_group: BrowserSelectorGroup | undefined;
}

export interface BlurCommand {
  selector: BrowserSelector | undefined;
  timeout: string | undefined;
  selector_group: BrowserSelectorGroup | undefined;
}

export interface HoverCommand {
  selector: BrowserSelector | undefined;
  position: BrowserPoint | undefined;
  timeout: string | undefined;
  selector_group: BrowserSelectorGroup | undefined;
}

export interface MouseMoveCommand {
  point: BrowserPoint | undefined;
  path: BrowserPoint[];
  duration: string | undefined;
}

export interface MouseClickCommand {
  point: BrowserPoint | undefined;
  button: BrowserMouseButton;
  click_count: number;
  delay: string | undefined;
  hold_duration: string | undefined;
}

export interface MouseDownCommand {
  button: BrowserMouseButton;
}

export interface MouseUpCommand {
  button: BrowserMouseButton;
}

export interface DragCommand {
  source_selector: BrowserSelector | undefined;
  target_selector: BrowserSelector | undefined;
  source_point: BrowserPoint | undefined;
  target_point: BrowserPoint | undefined;
  timeout: string | undefined;
  source_selector_group: BrowserSelectorGroup | undefined;
  target_selector_group: BrowserSelectorGroup | undefined;
}

export interface ScrollCommand {
  selector: BrowserSelector | undefined;
  selector_group: BrowserSelectorGroup | undefined;
  delta_x: number;
  delta_y: number;
  timeout: string | undefined;
}

export interface WaitForSelectorCommand {
  selector: BrowserSelector | undefined;
  state: BrowserSelectorState;
  timeout: string | undefined;
  selector_group: BrowserSelectorGroup | undefined;
}

export interface WaitForTextCommand {
  text: string;
  exact: boolean;
  timeout: string | undefined;
}

export interface WaitForURLCommand {
  url_pattern: string;
  exact: boolean;
  timeout: string | undefined;
}

export interface WaitForLoadStateCommand {
  state: BrowserLoadState;
  timeout: string | undefined;
}

export interface WaitForTimeoutCommand {
  duration: string | undefined;
}

export interface GetPageStateCommand {
  include_title: boolean;
  include_text: boolean;
  include_html: boolean;
}

export interface ExtractTextCommand {
  selector: BrowserSelector | undefined;
  all_matches: boolean;
  timeout: string | undefined;
  selector_group: BrowserSelectorGroup | undefined;
}

export interface GetAttributeCommand {
  selector: BrowserSelector | undefined;
  name: string;
  all_matches: boolean;
  timeout: string | undefined;
  selector_group: BrowserSelectorGroup | undefined;
}

export interface CountElementsCommand {
  selector: BrowserSelector | undefined;
  timeout: string | undefined;
  selector_group: BrowserSelectorGroup | undefined;
}

export interface ExtractElementCommand {
  selector: BrowserSelector | undefined;
  all_matches: boolean;
  include_text: boolean;
  include_html: boolean;
  include_attributes: boolean;
  attribute_names: string[];
  include_bounding_box: boolean;
  include_visibility: boolean;
  timeout: string | undefined;
  selector_group: BrowserSelectorGroup | undefined;
}

export interface ScreenshotCommand {
  selector: BrowserSelector | undefined;
  full_page: boolean;
  artifact_key: string;
  timeout: string | undefined;
  selector_group: BrowserSelectorGroup | undefined;
}

export interface UploadFileCommand {
  selector: BrowserSelector | undefined;
  file_secret_refs: SecretRef[];
  timeout: string | undefined;
  selector_group: BrowserSelectorGroup | undefined;
}

export interface SelectOptionCommand {
  selector: BrowserSelector | undefined;
  values: string[];
  labels: string[];
  indexes: number[];
  timeout: string | undefined;
  selector_group: BrowserSelectorGroup | undefined;
}

export interface SubmitFormCommand {
  selector: BrowserSelector | undefined;
  timeout: string | undefined;
  selector_group: BrowserSelectorGroup | undefined;
}

export interface EvaluateCommand {
  script_ref: string;
  args: { [key: string]: any } | undefined;
  timeout: string | undefined;
  inline_expression: string;
}

export interface GetCookiesCommand {
  urls: string[];
}

export interface GetStorageStateCommand {
  include_cookies: boolean;
  include_origins: boolean;
}

export interface BrowserNetworkRequestFilter {
  url_substring: string;
  url_regex: string;
  method: string;
  resource_type: string;
  status_code_min: number;
  status_code_max: number;
  started_after_unix_ms: number;
}

export interface WaitForNetworkRequestCommand {
  filter: BrowserNetworkRequestFilter | undefined;
  timeout: string | undefined;
  require_response: boolean;
}

export interface GetNetworkRequestsCommand {
  filter: BrowserNetworkRequestFilter | undefined;
  limit: number;
}

export interface BrowserCommand {
  command_id: string;
  command_key: string;
  timeout: string | undefined;
  continue_on_error: boolean;
  labels: { [key: string]: string };
  navigate?: NavigateCommand | undefined;
  click?: ClickCommand | undefined;
  fill?: FillCommand | undefined;
  press?: PressCommand | undefined;
  wait_for_selector?: WaitForSelectorCommand | undefined;
  wait_for_text?: WaitForTextCommand | undefined;
  extract_text?: ExtractTextCommand | undefined;
  screenshot?: ScreenshotCommand | undefined;
  upload_file?: UploadFileCommand | undefined;
  evaluate?: EvaluateCommand | undefined;
  select_option?: SelectOptionCommand | undefined;
  reload?: ReloadCommand | undefined;
  go_back?: GoBackCommand | undefined;
  go_forward?: GoForwardCommand | undefined;
  wait_for_url?: WaitForURLCommand | undefined;
  wait_for_load_state?: WaitForLoadStateCommand | undefined;
  wait_for_timeout?: WaitForTimeoutCommand | undefined;
  type_text?: TypeTextCommand | undefined;
  clear?: ClearCommand | undefined;
  focus?: FocusCommand | undefined;
  blur?: BlurCommand | undefined;
  hover?: HoverCommand | undefined;
  mouse_move?: MouseMoveCommand | undefined;
  mouse_click?: MouseClickCommand | undefined;
  mouse_down?: MouseDownCommand | undefined;
  mouse_up?: MouseUpCommand | undefined;
  drag?: DragCommand | undefined;
  submit_form?: SubmitFormCommand | undefined;
  get_attribute?: GetAttributeCommand | undefined;
  extract_element?: ExtractElementCommand | undefined;
  set_checked?: SetCheckedCommand | undefined;
  scroll?: ScrollCommand | undefined;
  get_page_state?: GetPageStateCommand | undefined;
  count_elements?: CountElementsCommand | undefined;
  get_cookies?: GetCookiesCommand | undefined;
  get_storage_state?: GetStorageStateCommand | undefined;
  wait_for_network_request?: WaitForNetworkRequestCommand | undefined;
  get_network_requests?: GetNetworkRequestsCommand | undefined;
}

export interface BrowserCommand_LabelsEntry {
  key: string;
  value: string;
}

export interface BrowserCommandResult {
  command_id: string;
  command_key: string;
  status: BrowserCommandStatus;
  error: BrowserAutomationError | undefined;
  text: string;
  texts: string[];
  json_value: any | undefined;
  artifact: BrowserArtifact | undefined;
  matched_count: number;
  current_url: string;
  attribute_value: string;
  attributes: { [key: string]: string };
  visible: boolean;
  bounding_box: BrowserRect | undefined;
  title: string;
  secret_ref: SecretRef | undefined;
  artifact_ref: ArtifactRef | undefined;
  completed_at: string | undefined;
}

export interface BrowserCommandResult_AttributesEntry {
  key: string;
  value: string;
}

export interface BrowserSession {
  session_id: string;
  request_id: string;
  status: BrowserSessionStatus;
  profile: BrowserProfile | undefined;
  last_error: BrowserAutomationError | undefined;
  artifacts: BrowserArtifact[];
  labels: { [key: string]: string };
  created_at: string | undefined;
  started_at: string | undefined;
  updated_at: string | undefined;
  stopped_at: string | undefined;
  expires_at: string | undefined;
}

export interface BrowserSession_LabelsEntry {
  key: string;
  value: string;
}

export interface BrowserTaskInput {
  session_id: string;
  task_key: string;
  scenario_key: string;
  target_url: string;
  timeout: string | undefined;
  commands: BrowserCommand[];
  security_policy: BrowserSecurityPolicy | undefined;
  labels: { [key: string]: string };
}

export interface BrowserTaskInput_LabelsEntry {
  key: string;
  value: string;
}

export interface BrowserTask {
  task_id: string;
  request_id: string;
  status: BrowserTaskStatus;
  input: BrowserTaskInput | undefined;
  last_error: BrowserAutomationError | undefined;
  artifacts: BrowserArtifact[];
  results: BrowserCommandResult[];
  labels: { [key: string]: string };
  created_at: string | undefined;
  started_at: string | undefined;
  updated_at: string | undefined;
  completed_at: string | undefined;
}

export interface BrowserTask_LabelsEntry {
  key: string;
  value: string;
}

export interface BrowserTaskFilter {
  session_id: string;
  status: BrowserTaskStatus;
  task_key: string;
  scenario_key: string;
  label_key: string;
  label_value: string;
  created_after: string | undefined;
  created_before: string | undefined;
}

export interface StartBrowserSessionRequest {
  request_id: string;
  profile: BrowserProfile | undefined;
  ttl: string | undefined;
  security_policy: BrowserSecurityPolicy | undefined;
  labels: { [key: string]: string };
}

export interface StartBrowserSessionRequest_LabelsEntry {
  key: string;
  value: string;
}

export interface StartBrowserSessionResponse {
  session: BrowserSession | undefined;
  error: BrowserAutomationError | undefined;
}

export interface GetBrowserSessionRequest {
  session_id: string;
}

export interface GetBrowserSessionResponse {
  session: BrowserSession | undefined;
  error: BrowserAutomationError | undefined;
}

export interface StopBrowserSessionRequest {
  session_id: string;
  reason: string;
}

export interface StopBrowserSessionResponse {
  session: BrowserSession | undefined;
  error: BrowserAutomationError | undefined;
}

export interface StartBrowserTaskRequest {
  request_id: string;
  input: BrowserTaskInput | undefined;
}

export interface StartBrowserTaskResponse {
  task: BrowserTask | undefined;
  error: BrowserAutomationError | undefined;
}

export interface ExecuteBrowserCommandsRequest {
  request_id: string;
  input: BrowserTaskInput | undefined;
}

export interface ExecuteBrowserCommandsResponse {
  task: BrowserTask | undefined;
  results: BrowserCommandResult[];
  error: BrowserAutomationError | undefined;
}

export interface GetBrowserTaskRequest {
  task_id: string;
}

export interface GetBrowserTaskResponse {
  task: BrowserTask | undefined;
  error: BrowserAutomationError | undefined;
}

export interface ListBrowserTasksRequest {
  filter: BrowserTaskFilter | undefined;
  page_size: number;
  page_token: string;
}

export interface ListBrowserTasksResponse {
  tasks: BrowserTask[];
  next_page_token: string;
  error: BrowserAutomationError | undefined;
}

export interface BrowserSessionStartedEvent {
  metadata: EventMetadata | undefined;
  session: BrowserSession | undefined;
}

export interface BrowserSessionStoppedEvent {
  metadata: EventMetadata | undefined;
  session_id: string;
  status: BrowserSessionStatus;
  reason: string;
}

export interface BrowserTaskStatusChangedEvent {
  metadata: EventMetadata | undefined;
  task_id: string;
  previous_status: BrowserTaskStatus;
  current_status: BrowserTaskStatus;
  reason: string;
}
