// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: byte/v/forge/contracts/mailbox/v1/mailbox.proto

/* eslint-disable */
import type { ArtifactRef, EventMetadata, SecretRef } from "../../common/v1/common";

export const protobufPackage = "byte.v.forge.contracts.mailbox.v1";

export enum EmailSignalKind {
  EMAIL_SIGNAL_KIND_UNSPECIFIED = "EMAIL_SIGNAL_KIND_UNSPECIFIED",
  EMAIL_SIGNAL_KIND_OTP = "EMAIL_SIGNAL_KIND_OTP",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum MailboxCredentialKind {
  MAILBOX_CREDENTIAL_KIND_UNSPECIFIED = "MAILBOX_CREDENTIAL_KIND_UNSPECIFIED",
  MAILBOX_CREDENTIAL_KIND_PASSWORD = "MAILBOX_CREDENTIAL_KIND_PASSWORD",
  MAILBOX_CREDENTIAL_KIND_OAUTH_REFRESH_TOKEN = "MAILBOX_CREDENTIAL_KIND_OAUTH_REFRESH_TOKEN",
  MAILBOX_CREDENTIAL_KIND_OAUTH_ACCESS_TOKEN = "MAILBOX_CREDENTIAL_KIND_OAUTH_ACCESS_TOKEN",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum MailboxAuthStatus {
  MAILBOX_AUTH_STATUS_UNSPECIFIED = "MAILBOX_AUTH_STATUS_UNSPECIFIED",
  MAILBOX_AUTH_STATUS_UNKNOWN = "MAILBOX_AUTH_STATUS_UNKNOWN",
  MAILBOX_AUTH_STATUS_OAUTH_PENDING = "MAILBOX_AUTH_STATUS_OAUTH_PENDING",
  MAILBOX_AUTH_STATUS_AUTHORIZED = "MAILBOX_AUTH_STATUS_AUTHORIZED",
  MAILBOX_AUTH_STATUS_AUTH_FAILED = "MAILBOX_AUTH_STATUS_AUTH_FAILED",
  MAILBOX_AUTH_STATUS_PASSWORD_ONLY = "MAILBOX_AUTH_STATUS_PASSWORD_ONLY",
  MAILBOX_AUTH_STATUS_WEBHOOK_ONLY = "MAILBOX_AUTH_STATUS_WEBHOOK_ONLY",
  MAILBOX_AUTH_STATUS_DISABLED = "MAILBOX_AUTH_STATUS_DISABLED",
  MAILBOX_AUTH_STATUS_NEEDS_MANUAL_VERIFICATION = "MAILBOX_AUTH_STATUS_NEEDS_MANUAL_VERIFICATION",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum MailboxOperationAction {
  MAILBOX_OPERATION_ACTION_UNSPECIFIED = "MAILBOX_OPERATION_ACTION_UNSPECIFIED",
  MAILBOX_OPERATION_ACTION_REGISTER_MAILBOX = "MAILBOX_OPERATION_ACTION_REGISTER_MAILBOX",
  MAILBOX_OPERATION_ACTION_MAILBOX_OAUTH = "MAILBOX_OPERATION_ACTION_MAILBOX_OAUTH",
  MAILBOX_OPERATION_ACTION_FETCH_INBOXES = "MAILBOX_OPERATION_ACTION_FETCH_INBOXES",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum MailboxOperationStatus {
  MAILBOX_OPERATION_STATUS_UNSPECIFIED = "MAILBOX_OPERATION_STATUS_UNSPECIFIED",
  MAILBOX_OPERATION_STATUS_CREATED = "MAILBOX_OPERATION_STATUS_CREATED",
  MAILBOX_OPERATION_STATUS_RUNNING = "MAILBOX_OPERATION_STATUS_RUNNING",
  MAILBOX_OPERATION_STATUS_SUCCEEDED = "MAILBOX_OPERATION_STATUS_SUCCEEDED",
  MAILBOX_OPERATION_STATUS_FAILED = "MAILBOX_OPERATION_STATUS_FAILED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum MailboxMessageRetentionScope {
  MAILBOX_MESSAGE_RETENTION_SCOPE_UNSPECIFIED = "MAILBOX_MESSAGE_RETENTION_SCOPE_UNSPECIFIED",
  MAILBOX_MESSAGE_RETENTION_SCOPE_MAILBOX = "MAILBOX_MESSAGE_RETENTION_SCOPE_MAILBOX",
  MAILBOX_MESSAGE_RETENTION_SCOPE_DOMAIN = "MAILBOX_MESSAGE_RETENTION_SCOPE_DOMAIN",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum MailboxProviderAction {
  MAILBOX_PROVIDER_ACTION_UNSPECIFIED = "MAILBOX_PROVIDER_ACTION_UNSPECIFIED",
  MAILBOX_PROVIDER_ACTION_IMPORT_MAILBOX = "MAILBOX_PROVIDER_ACTION_IMPORT_MAILBOX",
  MAILBOX_PROVIDER_ACTION_RUN_OAUTH = "MAILBOX_PROVIDER_ACTION_RUN_OAUTH",
  MAILBOX_PROVIDER_ACTION_FETCH_INBOX = "MAILBOX_PROVIDER_ACTION_FETCH_INBOX",
  MAILBOX_PROVIDER_ACTION_RECEIVE_WEBHOOK = "MAILBOX_PROVIDER_ACTION_RECEIVE_WEBHOOK",
  MAILBOX_PROVIDER_ACTION_AUTO_CREATE_MAILBOX = "MAILBOX_PROVIDER_ACTION_AUTO_CREATE_MAILBOX",
  MAILBOX_PROVIDER_ACTION_SYNC_DOMAINS = "MAILBOX_PROVIDER_ACTION_SYNC_DOMAINS",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface EmailSignal {
  kind: EmailSignalKind;
  secret_ref: SecretRef | undefined;
  label: string;
  profile: string;
  parser: string;
  confidence: number;
  evidence_preview: string;
}

export interface MailboxCredentialState {
  password_present: boolean;
  oauth_refresh_token_present: boolean;
  oauth_access_token_present: boolean;
  present_credentials: MailboxCredentialKind[];
}

export interface EmailMailbox {
  email_address: string;
  last_error: string;
  created_at: number;
  updated_at: number;
  auth_status: MailboxAuthStatus;
  latest_signal: EmailSignal | undefined;
  domain: string;
  credential_state: MailboxCredentialState | undefined;
  provider_key: string;
  credentials: MailboxCredentialValue[];
}

export interface MailboxCredentialInput {
  email_address: string;
  provider_key: string;
  credentials: MailboxCredentialValue[];
  auth_status: MailboxAuthStatus;
  last_error: string;
}

export interface MailboxCredentialValue {
  kind: MailboxCredentialKind;
  value: string;
}

export interface MarkEmailAuthStatusRequest {
  email_address: string;
  auth_status: MailboxAuthStatus;
  last_error: string;
}

export interface MarkEmailAuthStatusResponse {
  mailbox: EmailMailbox | undefined;
  error_message: string;
}

export interface UpsertEmailMailboxRequest {
  mailbox: MailboxCredentialInput | undefined;
}

export interface UpsertEmailMailboxResponse {
  mailbox: EmailMailbox | undefined;
  error_message: string;
}

export interface ListEmailMailboxesRequest {
  limit: number;
  auth_status: MailboxAuthStatus;
  provider_key: string;
  cursor: string;
  email_address: string;
}

export interface ListEmailMailboxesResponse {
  mailboxes: EmailMailbox[];
  next_cursor: string;
  error_message: string;
}

export interface DeleteMailboxRequest {
  email_address: string;
}

export interface DeleteMailboxResponse {
  deleted: boolean;
  error_message: string;
}

export interface EmailInboxMessage {
  id: string;
  mailbox_email: string;
  subject: string;
  from_address: string;
  body_preview: string;
  received_at_unix: number;
  recipients: string[];
  source_mailbox_email: string;
  body_artifact_ref: ArtifactRef | undefined;
  html_artifact_ref: ArtifactRef | undefined;
  raw_size: number;
  signals: EmailSignal[];
  primary_signal: EmailSignal | undefined;
  provider_key: string;
}

export interface MailboxEmailReceivedEvent {
  metadata: EventMetadata | undefined;
  message: EmailInboxMessage | undefined;
}

export interface MailboxEmailSignalReceivedEvent {
  metadata: EventMetadata | undefined;
  message: EmailInboxMessage | undefined;
  signal: EmailSignal | undefined;
}

export interface FetchMailboxInboxResult {
  mailbox: EmailMailbox | undefined;
  messages: EmailInboxMessage[];
  error_message: string;
}

export interface FetchMailboxInboxesRequest {
  limit_per_mailbox: number;
  max_mailboxes: number;
  email_address: string;
  parser_profile: string;
  received_after_unix: number;
}

export interface WaitForMailboxEmailRequest {
  email_address: string;
  subject_keyword: string;
  timeout_seconds: number;
  issued_after_unix: number;
  parser_profile: string;
  signal_kind: EmailSignalKind;
}

export interface WaitForMailboxEmailResponse {
  found: boolean;
  message: EmailInboxMessage | undefined;
}

export interface MailboxEmailPollRequest {
  email_address: string;
  subject_keyword: string;
  parser_profile: string;
  signal_kind: EmailSignalKind;
  issued_after_unix: number;
  deadline_unix: number;
  reason: string;
}

export interface ListMailboxInboxRequest {
  email_address: string;
  limit: number;
  parser_profile: string;
}

export interface ListMailboxInboxResponse {
  result: FetchMailboxInboxResult | undefined;
  error_message: string;
}

export interface FetchMailboxInboxesResponse {
  results: FetchMailboxInboxResult[];
  mailbox_count: number;
  fetched_count: number;
  failed_count: number;
  message_count: number;
  operation_id: string;
}

export interface RegisterMailboxRequest {
  import_only: boolean;
}

export interface RegisterMailboxResponse {
  operation_id: string;
  started: boolean;
  error_message: string;
}

export interface StartMailboxOAuthRequest {
  email_address: string;
  only_missing: boolean;
  limit: number;
}

export interface StartMailboxOAuthResponse {
  operation_id: string;
  started: boolean;
  error_message: string;
}

export interface MailboxOperation {
  operation_id: string;
  action: MailboxOperationAction;
  status: MailboxOperationStatus;
  email_address: string;
  last_step: string;
  error_message: string;
  exit_code: number;
  mailbox_count: number;
  fetched_count: number;
  failed_count: number;
  message_count: number;
  created_at: number;
  updated_at: number;
}

export interface GetMailboxOperationRequest {
  operation_id: string;
}

export interface GetMailboxOperationResponse {
  operation: MailboxOperation | undefined;
  error_message: string;
}

export interface ListMailboxOperationsRequest {
  limit: number;
  status: MailboxOperationStatus;
  action: MailboxOperationAction;
  email_address: string;
}

export interface ListMailboxOperationsResponse {
  operations: MailboxOperation[];
  error_message: string;
}

export interface MailboxDomain {
  domain: string;
  enabled: boolean;
  provider_key: string;
}

export interface ListMailboxDomainsRequest {
  provider_key: string;
}

export interface ListMailboxDomainsResponse {
  domains: MailboxDomain[];
  error_message: string;
}

export interface SyncMailboxDomainsRequest {
  provider_key: string;
}

export interface SyncMailboxDomainsResponse {
  domains: MailboxDomain[];
  synced_count: number;
  error_message: string;
}

export interface MailboxMessageRetentionPolicy {
  scope: MailboxMessageRetentionScope;
  max_messages: number;
}

export interface MailboxProviderActionCapability {
  action: MailboxProviderAction;
  required_credentials: MailboxCredentialKind[];
  required_auth_statuses: MailboxAuthStatus[];
  bulk_supported: boolean;
}

export interface MailboxProviderCapabilities {
  key: string;
  display_name: string;
  actions: MailboxProviderActionCapability[];
  retention_policy: MailboxMessageRetentionPolicy | undefined;
}

export interface ListMailboxProviderCapabilitiesRequest {
  provider_key: string;
}

export interface ListMailboxProviderCapabilitiesResponse {
  providers: MailboxProviderCapabilities[];
  error_message: string;
}
