// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: byte/v/forge/contracts/dashboard/v1/dashboard.proto

/* eslint-disable */

export const protobufPackage = "byte.v.forge.contracts.dashboard.v1";

export enum DashboardNavSection {
  DASHBOARD_NAV_SECTION_UNSPECIFIED = "DASHBOARD_NAV_SECTION_UNSPECIFIED",
  DASHBOARD_NAV_SECTION_MAIN = "DASHBOARD_NAV_SECTION_MAIN",
  DASHBOARD_NAV_SECTION_LAB = "DASHBOARD_NAV_SECTION_LAB",
  DASHBOARD_NAV_SECTION_INFRASTRUCTURE = "DASHBOARD_NAV_SECTION_INFRASTRUCTURE",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum DashboardServiceStatusState {
  DASHBOARD_SERVICE_STATUS_STATE_UNSPECIFIED = "DASHBOARD_SERVICE_STATUS_STATE_UNSPECIFIED",
  DASHBOARD_SERVICE_AVAILABLE = "DASHBOARD_SERVICE_AVAILABLE",
  DASHBOARD_SERVICE_UNAVAILABLE = "DASHBOARD_SERVICE_UNAVAILABLE",
  DASHBOARD_SERVICE_UNKNOWN = "DASHBOARD_SERVICE_UNKNOWN",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface DashboardModuleManifest {
  id: string;
  nav: DashboardNavEntry[];
}

export interface DashboardNavEntry {
  key: string;
  label: string;
  icon: string;
  section: DashboardNavSection;
  required_services: string[];
  order: number;
}

export interface DashboardServiceStatus {
  name: string;
  status: DashboardServiceStatusState;
  message: string;
  checked_at: string | undefined;
}

export interface DashboardServiceStatusResponse {
  services: DashboardServiceStatus[];
}
