// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: byte/v/forge/contracts/workflow/v1/workflow.proto

/* eslint-disable */
import type { EventContext } from "../../common/v1/common";

export const protobufPackage = "byte.v.forge.contracts.workflow.v1";

export enum WorkflowRuntimeStatus {
  WORKFLOW_RUNTIME_STATUS_UNSPECIFIED = "WORKFLOW_RUNTIME_STATUS_UNSPECIFIED",
  WORKFLOW_RUNTIME_AVAILABLE = "WORKFLOW_RUNTIME_AVAILABLE",
  WORKFLOW_RUNTIME_DEGRADED = "WORKFLOW_RUNTIME_DEGRADED",
  WORKFLOW_RUNTIME_UNCONFIGURED = "WORKFLOW_RUNTIME_UNCONFIGURED",
  WORKFLOW_RUNTIME_UNAVAILABLE = "WORKFLOW_RUNTIME_UNAVAILABLE",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum WorkflowRunStatus {
  WORKFLOW_RUN_STATUS_UNSPECIFIED = "WORKFLOW_RUN_STATUS_UNSPECIFIED",
  WORKFLOW_RUN_PENDING = "WORKFLOW_RUN_PENDING",
  WORKFLOW_RUN_RUNNING = "WORKFLOW_RUN_RUNNING",
  WORKFLOW_RUN_WAITING = "WORKFLOW_RUN_WAITING",
  WORKFLOW_RUN_SUCCEEDED = "WORKFLOW_RUN_SUCCEEDED",
  WORKFLOW_RUN_FAILED = "WORKFLOW_RUN_FAILED",
  WORKFLOW_RUN_CANCELED = "WORKFLOW_RUN_CANCELED",
  WORKFLOW_RUN_SKIPPED = "WORKFLOW_RUN_SKIPPED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface WorkflowRuntimeSummary {
  engine_status: WorkflowRuntimeStatus;
  engine_message: string;
  api_status: WorkflowRuntimeStatus;
  api_message: string;
  api_configured: boolean;
  editor_url: string;
  workflows: WorkflowDefinition[];
  executions: WorkflowExecution[];
  checked_at_unix: number;
  runs: WorkflowRunProjection[];
  runs_page_info: WorkflowRuntimePageInfo | undefined;
  executions_page_info: WorkflowRuntimePageInfo | undefined;
}

export interface WorkflowRuntimePageInfo {
  page_size: number;
  item_count: number;
  next_page_token: string;
}

export interface WorkflowDefinition {
  id: string;
  name: string;
  active: boolean;
  updated_at: string;
  tags: string[];
  graph_nodes: WorkflowGraphNode[];
  graph_edges: WorkflowGraphEdge[];
}

export interface WorkflowExecution {
  id: string;
  workflow_id: string;
  workflow_name: string;
  status: string;
  mode: string;
  started_at: string;
  stopped_at: string;
  graph_nodes: WorkflowGraphNode[];
  graph_edges: WorkflowGraphEdge[];
}

export interface WorkflowGraphNode {
  id: string;
  name: string;
  kind: string;
  status: string;
  x: number;
  y: number;
  type_version: string;
  disabled: boolean;
  started_at_unix: number;
  duration_ms: number;
  error_message: string;
  iterations: number;
}

export interface WorkflowGraphEdge {
  id: string;
  source: string;
  target: string;
  label: string;
  status: string;
}

export interface WorkflowRunProjection {
  run_id: string;
  workflow_id: string;
  workflow_name: string;
  execution_id: string;
  status: WorkflowRunStatus;
  current_node_id: string;
  current_node_name: string;
  error_message: string;
  started_at_unix: number;
  completed_at_unix: number;
  updated_at_unix: number;
  graph_nodes: WorkflowGraphNode[];
  graph_edges: WorkflowGraphEdge[];
}

export interface WorkflowStepUpdateRequest {
  run_id: string;
  workflow_id: string;
  workflow_name: string;
  execution_id: string;
  node_id: string;
  node_name: string;
  status: WorkflowRunStatus;
  error_message: string;
  occurred_at_unix: number;
  context: EventContext | undefined;
}

export interface WorkflowStepUpdateResponse {
  run: WorkflowRunProjection | undefined;
  duplicate: boolean;
}
