// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: byte/v/forge/contracts/workflow/v1/workflow.proto

/* eslint-disable */

export const protobufPackage = "byte.v.forge.contracts.workflow.v1";

export enum WorkflowRuntimeStatus {
  WORKFLOW_RUNTIME_STATUS_UNSPECIFIED = "WORKFLOW_RUNTIME_STATUS_UNSPECIFIED",
  WORKFLOW_RUNTIME_AVAILABLE = "WORKFLOW_RUNTIME_AVAILABLE",
  WORKFLOW_RUNTIME_DEGRADED = "WORKFLOW_RUNTIME_DEGRADED",
  WORKFLOW_RUNTIME_UNCONFIGURED = "WORKFLOW_RUNTIME_UNCONFIGURED",
  WORKFLOW_RUNTIME_UNAVAILABLE = "WORKFLOW_RUNTIME_UNAVAILABLE",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface WorkflowRuntimeSummary {
  engine_status: WorkflowRuntimeStatus;
  engine_message: string;
  api_status: WorkflowRuntimeStatus;
  api_message: string;
  api_configured: boolean;
  editor_url: string;
  workflows: WorkflowDefinition[];
  executions: WorkflowExecution[];
  checked_at_unix: number;
}

export interface WorkflowDefinition {
  id: string;
  name: string;
  active: boolean;
  updated_at: string;
  tags: string[];
}

export interface WorkflowExecution {
  id: string;
  workflow_id: string;
  workflow_name: string;
  status: string;
  mode: string;
  started_at: string;
  stopped_at: string;
}
