// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: byte/v/forge/contracts/observability/v1/hotstream.proto

/* eslint-disable */
import type { EventMetadata } from "../../common/v1/common";

export const protobufPackage = "byte.v.forge.contracts.observability.v1";

export enum HotStreamControlKind {
  HOT_STREAM_CONTROL_KIND_UNSPECIFIED = "HOT_STREAM_CONTROL_KIND_UNSPECIFIED",
  HOT_STREAM_CONTROL_KIND_CONNECTED = "HOT_STREAM_CONTROL_KIND_CONNECTED",
  HOT_STREAM_CONTROL_KIND_HEARTBEAT = "HOT_STREAM_CONTROL_KIND_HEARTBEAT",
  HOT_STREAM_CONTROL_KIND_RESYNC_REQUIRED = "HOT_STREAM_CONTROL_KIND_RESYNC_REQUIRED",
  HOT_STREAM_CONTROL_KIND_ERROR = "HOT_STREAM_CONTROL_KIND_ERROR",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface HotStreamEvent {
  metadata: EventMetadata | undefined;
  resource_type: string;
  resource_id: string;
  scope: string;
  attributes: { [key: string]: string };
}

export interface HotStreamEvent_AttributesEntry {
  key: string;
  value: string;
}

export interface HotStreamControlEvent {
  kind: HotStreamControlKind;
  message: string;
  occurred_at: string | undefined;
  attributes: { [key: string]: string };
}

export interface HotStreamControlEvent_AttributesEntry {
  key: string;
  value: string;
}
